import { defineSchema } from "convex/server";
import {
  usersTable,
  orgsTable,
  membershipsTable,
  servicesTable,
  orgServicesTable,
  profilesTable,
  requestsTable,
  eventsTable,
  documentsTable,
  documentFoldersTable,
  postsTable,
  conversationsTable,
  formTemplatesTable,
  appointmentsTable,
  agentSchedulesTable,
  messagesTable,
  documentTemplatesTable,
  documentTemplateVersionsTable,
  templateHeaderFooterBlocksTable,
  templateTypographyBlocksTable,
  templateVoiceBlocksTable,
  generatedDocumentsTable,
  paymentsTable,
  documentVerificationsTable,
  agentNotesTable,
  consularRegistrationsTable,
  consularNotificationsTable,
  cvTable,
  childProfilesTable,
  auditLogTable,
  notificationsTable,
  tutorialsTable,
  communityEventsTable,
  digitalMailTable,
  deliveryPackagesTable,
  associationsTable,
  associationMembersTable,
  associationClaimsTable,
  companiesTable,
  companyMembersTable,
  positionsTable,
  ministryGroupsTable,
  securityPoliciesTable,
  maintenanceConfigTable,
  ticketsTable,
  meetingsTable,
  callLinesTable,
  agentPresenceTable,
  countersTable,
  signauxTable,
  historiqueActionsTable,
  configSystemeTable,
  metriquesTable,
  poidsAdaptatifsTable,
  gcpMetricsCacheTable,
  cardDesignsTable,
  printJobsTable,
  correspondanceFoldersTable,
  correspondanceItemsTable,
  correspondanceWorkflowStepsTable,
  correspondanceRecipientsTable,
  correspondanceTypeConfigsTable,
  correspondanceApprovalStepsTable,
  typeDemarchesTable,
  dossierProceduresTable,
  dossierPiecesTable,
  dossierTransitionsTable,
  copiesPassageTable,
  journalActionsTable,
  diplomaticTargetsTable,
  diplomaticLettersTable,
  diplomaticPlansTable,
  diplomaticReportsTable,
  diplomaticProjectsTable,
  diplomaticPrioritiesTable,
  diplomaticDocumentsTable,
  chatsTable,
  chatMessagesTable,
  ipThreatScoresTable,
  guidesTable,
  archivePoliciesTable,
  archiveAuditLogTable,
  orgCalendarTable,
  missedCallsTable,
  orgIAstedConfigTable,
  orgRoleTemplatesTable,
  orgEscalationPolicyTable,
  callRecordingsTable,
  voicemailsTable,
  supervisionSessionsTable,
  pushSubscriptionsTable,
  callNotesTable,
  draftMessagesTable,
} from "./schemas";

export default defineSchema({
  users: usersTable,
  orgs: orgsTable,
  memberships: membershipsTable,
  services: servicesTable,
  orgServices: orgServicesTable,
  profiles: profilesTable,
  requests: requestsTable,
  events: eventsTable,
  documents: documentsTable,
  documentFolders: documentFoldersTable,
  posts: postsTable,
  conversations: conversationsTable,
  formTemplates: formTemplatesTable,
  appointments: appointmentsTable,
  agentSchedules: agentSchedulesTable,
  messages: messagesTable,
  documentTemplates: documentTemplatesTable,
  documentTemplateVersions: documentTemplateVersionsTable,
  // Briques modulaires composées par un template (Entête/Pied, Typo, Voix IA)
  templateHeaderFooterBlocks: templateHeaderFooterBlocksTable,
  templateTypographyBlocks: templateTypographyBlocksTable,
  templateVoiceBlocks: templateVoiceBlocksTable,
  generatedDocuments: generatedDocumentsTable,
  payments: paymentsTable,
  documentVerifications: documentVerificationsTable,
  agentNotes: agentNotesTable,
  consularRegistrations: consularRegistrationsTable,
  consularNotifications: consularNotificationsTable,
  cv: cvTable,
  childProfiles: childProfilesTable,
  auditLog: auditLogTable,
  notifications: notificationsTable,
  tutorials: tutorialsTable,
  communityEvents: communityEventsTable,
  digitalMail: digitalMailTable,
  deliveryPackages: deliveryPackagesTable,
  associations: associationsTable,
  associationMembers: associationMembersTable,
  associationClaims: associationClaimsTable,
  companies: companiesTable,
  companyMembers: companyMembersTable,
  positions: positionsTable,
  ministryGroups: ministryGroupsTable,
  securityPolicies: securityPoliciesTable,
  maintenanceConfig: maintenanceConfigTable,
  tickets: ticketsTable,
  meetings: meetingsTable,
  callLines: callLinesTable,
  agentPresence: agentPresenceTable,
  counters: countersTable,
  signaux: signauxTable,
  historiqueActions: historiqueActionsTable,
  configSysteme: configSystemeTable,
  metriques: metriquesTable,
  poidsAdaptatifs: poidsAdaptatifsTable,
  gcpMetricsCache: gcpMetricsCacheTable,
  cardDesigns: cardDesignsTable,
  printJobs: printJobsTable,
  correspondanceFolders: correspondanceFoldersTable,
  correspondanceItems: correspondanceItemsTable,
  correspondanceWorkflowSteps: correspondanceWorkflowStepsTable,
  correspondanceRecipients: correspondanceRecipientsTable,
  correspondanceTypeConfigs: correspondanceTypeConfigsTable,
  correspondanceApprovalSteps: correspondanceApprovalStepsTable,
  typeDemarches: typeDemarchesTable,
  dossierProcedures: dossierProceduresTable,
  dossierPieces: dossierPiecesTable,
  dossierTransitions: dossierTransitionsTable,
  copiesPassage: copiesPassageTable,
  journalActions: journalActionsTable,
  // Affaires Diplomatiques — Pipeline IA
  diplomaticTargets: diplomaticTargetsTable,
  diplomaticLetters: diplomaticLettersTable,
  diplomaticPlans: diplomaticPlansTable,
  diplomaticReports: diplomaticReportsTable,
  diplomaticProjects: diplomaticProjectsTable,
  diplomaticPriorities: diplomaticPrioritiesTable,
  diplomaticDocuments: diplomaticDocumentsTable,
  // Chat peer-to-peer
  chats: chatsTable,
  chatMessages: chatMessagesTable,
  // Defense automatique
  ipThreatScores: ipThreatScoresTable,
  // Guides
  guides: guidesTable,
  // iArchive — Politiques et audit d'archivage
  archivePolicies: archivePoliciesTable,
  archiveAuditLog: archiveAuditLogTable,
  // Phase 1 Fondations — Paramétrage représentation (horaires, jours fériés, fermetures)
  orgCalendar: orgCalendarTable,
  // Phase 2 Communication — Extensions iAppel (appels manqués)
  missedCalls: missedCallsTable,
  // Phase 3 iAsted — Configuration chatbot par représentation
  orgIAstedConfig: orgIAstedConfigTable,
  // Phase C3 — Templates de rôles personnalisables par org
  orgRoleTemplates: orgRoleTemplatesTable,
  // Phase D3 — Politique d'escalation unifiée (chatbot + callcenter)
  orgEscalationPolicy: orgEscalationPolicyTable,
  // iAppel — Enregistrements, voicemails, supervision
  callRecordings: callRecordingsTable,
  voicemails: voicemailsTable,
  supervisionSessions: supervisionSessionsTable,
  // Notifications — Web Push subscriptions
  pushSubscriptions: pushSubscriptionsTable,
  // Sprint 6 — Notes post-appel + brouillons de messages
  callNotes: callNotesTable,
  draftMessages: draftMessagesTable,
});
