import { defineSchema } from "convex/server";
import {
  usersTable,
  orgsTable,
  membershipsTable,
  servicesTable,
  orgServicesTable,
  profilesTable,
  requestsTable,
  eventsTable,
  documentsTable,
  documentFoldersTable,
  postsTable,
  conversationsTable,
  formTemplatesTable,
  appointmentsTable,
  agentSchedulesTable,
  messagesTable,
  documentTemplatesTable,
  paymentsTable,
  documentVerificationsTable,
  agentNotesTable,
  consularRegistrationsTable,
  consularNotificationsTable,
  cvTable,
  childProfilesTable,
  auditLogTable,
  notificationsTable,
  tutorialsTable,
  communityEventsTable,
  digitalMailTable,
  deliveryPackagesTable,
  associationsTable,
  associationMembersTable,
  associationClaimsTable,
  companiesTable,
  companyMembersTable,
  positionsTable,
  ministryGroupsTable,
  securityPoliciesTable,
  maintenanceConfigTable,
  ticketsTable,
  meetingsTable,
  callLinesTable,
  countersTable,
  signauxTable,
  historiqueActionsTable,
  configSystemeTable,
  metriquesTable,
  poidsAdaptatifsTable,
  gcpMetricsCacheTable,
  cardDesignsTable,
  printJobsTable,
  correspondanceFoldersTable,
  correspondanceItemsTable,
  correspondanceWorkflowStepsTable,
  correspondanceRecipientsTable,
  correspondanceTypeConfigsTable,
  correspondanceApprovalStepsTable,
  typeDemarchesTable,
  dossierProceduresTable,
  dossierPiecesTable,
  dossierTransitionsTable,
  copiesPassageTable,
  journalActionsTable,
  diplomaticTargetsTable,
  diplomaticLettersTable,
  diplomaticPlansTable,
  diplomaticReportsTable,
  diplomaticProjectsTable,
  diplomaticPrioritiesTable,
  diplomaticDocumentsTable,
  chatsTable,
  chatMessagesTable,
  ipThreatScoresTable,
  guidesTable,
  archivePoliciesTable,
  archiveAuditLogTable,
} from "./schemas";

export default defineSchema({
  users: usersTable,
  orgs: orgsTable,
  memberships: membershipsTable,
  services: servicesTable,
  orgServices: orgServicesTable,
  profiles: profilesTable,
  requests: requestsTable,
  events: eventsTable,
  documents: documentsTable,
  documentFolders: documentFoldersTable,
  posts: postsTable,
  conversations: conversationsTable,
  formTemplates: formTemplatesTable,
  appointments: appointmentsTable,
  agentSchedules: agentSchedulesTable,
  messages: messagesTable,
  documentTemplates: documentTemplatesTable,
  payments: paymentsTable,
  documentVerifications: documentVerificationsTable,
  agentNotes: agentNotesTable,
  consularRegistrations: consularRegistrationsTable,
  consularNotifications: consularNotificationsTable,
  cv: cvTable,
  childProfiles: childProfilesTable,
  auditLog: auditLogTable,
  notifications: notificationsTable,
  tutorials: tutorialsTable,
  communityEvents: communityEventsTable,
  digitalMail: digitalMailTable,
  deliveryPackages: deliveryPackagesTable,
  associations: associationsTable,
  associationMembers: associationMembersTable,
  associationClaims: associationClaimsTable,
  companies: companiesTable,
  companyMembers: companyMembersTable,
  positions: positionsTable,
  ministryGroups: ministryGroupsTable,
  securityPolicies: securityPoliciesTable,
  maintenanceConfig: maintenanceConfigTable,
  tickets: ticketsTable,
  meetings: meetingsTable,
  callLines: callLinesTable,
  counters: countersTable,
  signaux: signauxTable,
  historiqueActions: historiqueActionsTable,
  configSysteme: configSystemeTable,
  metriques: metriquesTable,
  poidsAdaptatifs: poidsAdaptatifsTable,
  gcpMetricsCache: gcpMetricsCacheTable,
  cardDesigns: cardDesignsTable,
  printJobs: printJobsTable,
  correspondanceFolders: correspondanceFoldersTable,
  correspondanceItems: correspondanceItemsTable,
  correspondanceWorkflowSteps: correspondanceWorkflowStepsTable,
  correspondanceRecipients: correspondanceRecipientsTable,
  correspondanceTypeConfigs: correspondanceTypeConfigsTable,
  correspondanceApprovalSteps: correspondanceApprovalStepsTable,
  typeDemarches: typeDemarchesTable,
  dossierProcedures: dossierProceduresTable,
  dossierPieces: dossierPiecesTable,
  dossierTransitions: dossierTransitionsTable,
  copiesPassage: copiesPassageTable,
  journalActions: journalActionsTable,
  // Affaires Diplomatiques — Pipeline IA
  diplomaticTargets: diplomaticTargetsTable,
  diplomaticLetters: diplomaticLettersTable,
  diplomaticPlans: diplomaticPlansTable,
  diplomaticReports: diplomaticReportsTable,
  diplomaticProjects: diplomaticProjectsTable,
  diplomaticPriorities: diplomaticPrioritiesTable,
  diplomaticDocuments: diplomaticDocumentsTable,
  // Chat peer-to-peer
  chats: chatsTable,
  chatMessages: chatMessagesTable,
  // Defense automatique
  ipThreatScores: ipThreatScoresTable,
  // Guides
  guides: guidesTable,
  // iArchive — Politiques et audit d'archivage
  archivePolicies: archivePoliciesTable,
  archiveAuditLog: archiveAuditLogTable,
});
