import { defineSchema } from "convex/server";
import {
  usersTable,
  orgsTable,
  membershipsTable,
  servicesTable,
  orgServicesTable,
  profilesTable,
  requestsTable,
  eventsTable,
  documentsTable,
  documentFoldersTable,
  postsTable,
  conversationsTable,
  streamingChatsTable,
  formTemplatesTable,
  appointmentsTable,
  appointmentWaitlistTable,
  agentSchedulesTable,
  messagesTable,
  documentTemplatesTable,
  documentTemplateVersionsTable,
  generatedDocumentsTable,
  documentVerificationsTable,
  agentNotesTable,
  profileNotesTable,
  intelligenceNotesTable,
  intelligenceWatchlistsTable,
  intelligenceWatchlistItemsTable,
  intelligenceLinksTable,
  intelligenceAuditLogTable,
  intelligenceAlertRulesTable,
  intelligenceAlertsTable,
  intelligenceCasesTable,
  intelligenceCaseEntitiesTable,
  intelligenceCaseEventsTable,
  intelligenceEnclavesTable,
  intelligenceBriefingsTable,
  consularRegistrationsTable,
  consularNotificationsTable,
  cvTable,
  childProfilesTable,
  auditLogTable,
  notificationsTable,
  tutorialsTable,
  tutorialProgressTable,
  faqsTable,
  orgPublicDocumentsTable,
  communityEventsTable,
  digitalMailTable,
  deliveryPackagesTable,
  associationsTable,
  associationMembersTable,
  associationClaimsTable,
  companiesTable,
  companyMembersTable,
  positionsTable,
  ministryGroupsTable,
  securityPoliciesTable,
  maintenanceConfigTable,
  ticketsTable,
  meetingsTable,
  callLinesTable,
  agentPresenceTable,
  countersTable,
  signauxTable,
  historiqueActionsTable,
  configSystemeTable,
  metriquesTable,
  poidsAdaptatifsTable,
  gcpMetricsCacheTable,
  cardDesignsTable,
  printJobsTable,
  correspondanceFoldersTable,
  correspondanceItemsTable,
  correspondanceWorkflowStepsTable,
  correspondanceRecipientsTable,
  correspondanceTypeConfigsTable,
  correspondanceApprovalStepsTable,
  correspondanceAnnotationsTable,
  correspondanceSignaturesTable,
  typeDemarchesTable,
  dossierProceduresTable,
  dossierPiecesTable,
  dossierTransitionsTable,
  copiesPassageTable,
  journalActionsTable,
  diplomaticTargetsTable,
  diplomaticLettersTable,
  diplomaticPlansTable,
  diplomaticReportsTable,
  diplomaticProjectsTable,
  diplomaticPrioritiesTable,
  diplomaticDocumentsTable,
  chatsTable,
  chatMessagesTable,
  chatTypingTable,
  ipThreatScoresTable,
  guidesTable,
  archivePoliciesTable,
  archiveAuditLogTable,
  orgCalendarTable,
  missedCallsTable,
  orgIAstedConfigTable,
  orgRoleTemplatesTable,
  orgEscalationPolicyTable,
  callRecordingsTable,
  voicemailsTable,
  supervisionSessionsTable,
  pushSubscriptionsTable,
  callNotesTable,
  draftMessagesTable,
  aiSuggestionsTable,
  aiActivityLogTable,
  userAIPreferencesTable,
  aiAgentPresenceTable,
  aiCapabilityConfigTable,
  newsletterSubscriptionsTable,
} from "./schemas";

export default defineSchema({
  users: usersTable,
  orgs: orgsTable,
  memberships: membershipsTable,
  services: servicesTable,
  orgServices: orgServicesTable,
  profiles: profilesTable,
  requests: requestsTable,
  events: eventsTable,
  documents: documentsTable,
  documentFolders: documentFoldersTable,
  posts: postsTable,
  conversations: conversationsTable,
  streamingChats: streamingChatsTable,
  formTemplates: formTemplatesTable,
  appointments: appointmentsTable,
  appointmentWaitlist: appointmentWaitlistTable,
  agentSchedules: agentSchedulesTable,
  messages: messagesTable,
  documentTemplates: documentTemplatesTable,
  documentTemplateVersions: documentTemplateVersionsTable,
  generatedDocuments: generatedDocumentsTable,
  documentVerifications: documentVerificationsTable,
  agentNotes: agentNotesTable,
  profileNotes: profileNotesTable,
  intelligenceNotes: intelligenceNotesTable,
  intelligenceWatchlists: intelligenceWatchlistsTable,
  intelligenceWatchlistItems: intelligenceWatchlistItemsTable,
  intelligenceLinks: intelligenceLinksTable,
  intelligenceAuditLog: intelligenceAuditLogTable,
  intelligenceAlertRules: intelligenceAlertRulesTable,
  intelligenceAlerts: intelligenceAlertsTable,
  intelligenceCases: intelligenceCasesTable,
  intelligenceCaseEntities: intelligenceCaseEntitiesTable,
  intelligenceCaseEvents: intelligenceCaseEventsTable,
  intelligenceEnclaves: intelligenceEnclavesTable,
  intelligenceBriefings: intelligenceBriefingsTable,
  consularRegistrations: consularRegistrationsTable,
  consularNotifications: consularNotificationsTable,
  cv: cvTable,
  childProfiles: childProfilesTable,
  auditLog: auditLogTable,
  notifications: notificationsTable,
  tutorials: tutorialsTable,
  tutorialProgress: tutorialProgressTable,
  faqs: faqsTable,
  orgPublicDocuments: orgPublicDocumentsTable,
  communityEvents: communityEventsTable,
  digitalMail: digitalMailTable,
  deliveryPackages: deliveryPackagesTable,
  associations: associationsTable,
  associationMembers: associationMembersTable,
  associationClaims: associationClaimsTable,
  companies: companiesTable,
  companyMembers: companyMembersTable,
  positions: positionsTable,
  ministryGroups: ministryGroupsTable,
  securityPolicies: securityPoliciesTable,
  maintenanceConfig: maintenanceConfigTable,
  tickets: ticketsTable,
  meetings: meetingsTable,
  callLines: callLinesTable,
  agentPresence: agentPresenceTable,
  counters: countersTable,
  signaux: signauxTable,
  historiqueActions: historiqueActionsTable,
  configSysteme: configSystemeTable,
  metriques: metriquesTable,
  poidsAdaptatifs: poidsAdaptatifsTable,
  gcpMetricsCache: gcpMetricsCacheTable,
  cardDesigns: cardDesignsTable,
  printJobs: printJobsTable,
  correspondanceFolders: correspondanceFoldersTable,
  correspondanceItems: correspondanceItemsTable,
  correspondanceWorkflowSteps: correspondanceWorkflowStepsTable,
  correspondanceRecipients: correspondanceRecipientsTable,
  correspondanceTypeConfigs: correspondanceTypeConfigsTable,
  correspondanceApprovalSteps: correspondanceApprovalStepsTable,
  correspondanceAnnotations: correspondanceAnnotationsTable,
  correspondanceSignatures: correspondanceSignaturesTable,
  typeDemarches: typeDemarchesTable,
  dossierProcedures: dossierProceduresTable,
  dossierPieces: dossierPiecesTable,
  dossierTransitions: dossierTransitionsTable,
  copiesPassage: copiesPassageTable,
  journalActions: journalActionsTable,
  // Affaires Diplomatiques — Pipeline IA
  diplomaticTargets: diplomaticTargetsTable,
  diplomaticLetters: diplomaticLettersTable,
  diplomaticPlans: diplomaticPlansTable,
  diplomaticReports: diplomaticReportsTable,
  diplomaticProjects: diplomaticProjectsTable,
  diplomaticPriorities: diplomaticPrioritiesTable,
  diplomaticDocuments: diplomaticDocumentsTable,
  // Chat peer-to-peer
  chats: chatsTable,
  chatMessages: chatMessagesTable,
  chatTyping: chatTypingTable,
  // Defense automatique
  ipThreatScores: ipThreatScoresTable,
  // Guides
  guides: guidesTable,
  // iArchive — Politiques et audit d'archivage
  archivePolicies: archivePoliciesTable,
  archiveAuditLog: archiveAuditLogTable,
  // Phase 1 Fondations — Paramétrage représentation (horaires, jours fériés, fermetures)
  orgCalendar: orgCalendarTable,
  // Phase 2 Communication — Extensions iAppel (appels manqués)
  missedCalls: missedCallsTable,
  // Phase 3 iAsted — Configuration chatbot par représentation
  orgIAstedConfig: orgIAstedConfigTable,
  // Phase C3 — Templates de rôles personnalisables par org
  orgRoleTemplates: orgRoleTemplatesTable,
  // Phase D3 — Politique d'escalation unifiée (chatbot + callcenter)
  orgEscalationPolicy: orgEscalationPolicyTable,
  // iAppel — Enregistrements, voicemails, supervision
  callRecordings: callRecordingsTable,
  voicemails: voicemailsTable,
  supervisionSessions: supervisionSessionsTable,
  // Notifications — Web Push subscriptions
  pushSubscriptions: pushSubscriptionsTable,
  // Sprint 6 — Notes post-appel + brouillons de messages
  callNotes: callNotesTable,
  draftMessages: draftMessagesTable,
  // Agent IA Proactif — Module ai_assistant
  aiSuggestions: aiSuggestionsTable,
  aiActivityLog: aiActivityLogTable,
  userAIPreferences: userAIPreferencesTable,
  aiAgentPresence: aiAgentPresenceTable,
  aiCapabilityConfig: aiCapabilityConfigTable,
  newsletterSubscriptions: newsletterSubscriptionsTable,
});
