/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as actions_gcpMonitoring from "../actions/gcpMonitoring.js";
import type * as actions_iAstedPromptGenerator from "../actions/iAstedPromptGenerator.js";
import type * as actions_intelligenceBriefings from "../actions/intelligenceBriefings.js";
import type * as actions_livekit from "../actions/livekit.js";
import type * as actions_posthog from "../actions/posthog.js";
import type * as actions_posthogHealthCheck from "../actions/posthogHealthCheck.js";
import type * as actions_push from "../actions/push.js";
import type * as ai_activityLog from "../ai/activityLog.js";
import type * as ai_adminChat from "../ai/adminChat.js";
import type * as ai_adminChatStreaming from "../ai/adminChatStreaming.js";
import type * as ai_adminContext from "../ai/adminContext.js";
import type * as ai_adminToolExecutor from "../ai/adminToolExecutor.js";
import type * as ai_adminTools from "../ai/adminTools.js";
import type * as ai_adminVoice from "../ai/adminVoice.js";
import type * as ai_aiTriggers from "../ai/aiTriggers.js";
import type * as ai_assets_idPhotoGuide from "../ai/assets/idPhotoGuide.js";
import type * as ai_capabilities__types from "../ai/capabilities/_types.js";
import type * as ai_capabilities_autoSummary from "../ai/capabilities/autoSummary.js";
import type * as ai_capabilities_bulkActionsHelper from "../ai/capabilities/bulkActionsHelper.js";
import type * as ai_capabilities_complianceCheck from "../ai/capabilities/complianceCheck.js";
import type * as ai_capabilities_correspondanceDrafting from "../ai/capabilities/correspondanceDrafting.js";
import type * as ai_capabilities_documentAnalysis from "../ai/capabilities/documentAnalysis.js";
import type * as ai_capabilities_documentDrafting from "../ai/capabilities/documentDrafting.js";
import type * as ai_capabilities_meetingPrep from "../ai/capabilities/meetingPrep.js";
import type * as ai_capabilities_nextStepSuggestion from "../ai/capabilities/nextStepSuggestion.js";
import type * as ai_capabilities_proactiveNotifications from "../ai/capabilities/proactiveNotifications.js";
import type * as ai_capabilities_requestTriage from "../ai/capabilities/requestTriage.js";
import type * as ai_capabilities_riskDetection from "../ai/capabilities/riskDetection.js";
import type * as ai_capabilities_voiceAssist from "../ai/capabilities/voiceAssist.js";
import type * as ai_capabilitiesData from "../ai/capabilitiesData.js";
import type * as ai_capabilityRegistry from "../ai/capabilityRegistry.js";
import type * as ai_chat from "../ai/chat.js";
import type * as ai_contextStore from "../ai/contextStore.js";
import type * as ai_dashboardAI from "../ai/dashboardAI.js";
import type * as ai_diplomaticAI from "../ai/diplomaticAI.js";
import type * as ai_dispatcher from "../ai/dispatcher.js";
import type * as ai_documentAnalysis from "../ai/documentAnalysis.js";
import type * as ai_documentExtraction from "../ai/documentExtraction.js";
import type * as ai_iastedConversations from "../ai/iastedConversations.js";
import type * as ai_iastedDelegationHelpers from "../ai/iastedDelegationHelpers.js";
import type * as ai_iastedDevicePresence from "../ai/iastedDevicePresence.js";
import type * as ai_iastedMeetingSummariesHelpers from "../ai/iastedMeetingSummariesHelpers.js";
import type * as ai_iastedMemories from "../ai/iastedMemories.js";
import type * as ai_iastedPatternMining from "../ai/iastedPatternMining.js";
import type * as ai_iastedRealtimePrompt from "../ai/iastedRealtimePrompt.js";
import type * as ai_mrRay from "../ai/mrRay.js";
import type * as ai_preferences from "../ai/preferences.js";
import type * as ai_proactiveAgent from "../ai/proactiveAgent.js";
import type * as ai_proactiveRouter from "../ai/proactiveRouter.js";
import type * as ai_providers_anthropic from "../ai/providers/anthropic.js";
import type * as ai_providers_gemini from "../ai/providers/gemini.js";
import type * as ai_publicChat from "../ai/publicChat.js";
import type * as ai_rag_embeddingService from "../ai/rag/embeddingService.js";
import type * as ai_rag_indexer from "../ai/rag/indexer.js";
import type * as ai_rag_retriever from "../ai/rag/retriever.js";
import type * as ai_rateLimiter from "../ai/rateLimiter.js";
import type * as ai_realtimeAvailable from "../ai/realtimeAvailable.js";
import type * as ai_realtimeKnowledge from "../ai/realtimeKnowledge.js";
import type * as ai_realtimeSessions from "../ai/realtimeSessions.js";
import type * as ai_realtimeToken from "../ai/realtimeToken.js";
import type * as ai_realtimeToolExecutor from "../ai/realtimeToolExecutor.js";
import type * as ai_realtimeTools from "../ai/realtimeTools.js";
import type * as ai_realtimeTypes from "../ai/realtimeTypes.js";
import type * as ai_routes_manifest from "../ai/routes_manifest.js";
import type * as ai_scheduledSweeper from "../ai/scheduledSweeper.js";
import type * as ai_securityGuardian from "../ai/securityGuardian.js";
import type * as ai_streamingChats from "../ai/streamingChats.js";
import type * as ai_suggestions from "../ai/suggestions.js";
import type * as ai_tools from "../ai/tools.js";
import type * as ai_userIdentity from "../ai/userIdentity.js";
import type * as ai_userLexicon from "../ai/userLexicon.js";
import type * as ai_vision from "../ai/vision.js";
import type * as ai_voice from "../ai/voice.js";
import type * as ai_voicePreferences from "../ai/voicePreferences.js";
import type * as ai_voicePrints from "../ai/voicePrints.js";
import type * as assets_sceauGabonBase64 from "../assets/sceauGabonBase64.js";
import type * as auditif from "../auditif.js";
import type * as betterAuth_auth from "../betterAuth/auth.js";
import type * as crons from "../crons.js";
import type * as crons_archiveExpiration from "../crons/archiveExpiration.js";
import type * as crons_correspondanceSla from "../crons/correspondanceSla.js";
import type * as crons_expiration from "../crons/expiration.js";
import type * as crons_posthogHealthCheck from "../crons/posthogHealthCheck.js";
import type * as functions_admin from "../functions/admin.js";
import type * as functions_adminSkills from "../functions/adminSkills.js";
import type * as functions_adminSkillsActions from "../functions/adminSkillsActions.js";
import type * as functions_agentNotes from "../functions/agentNotes.js";
import type * as functions_agentPresence from "../functions/agentPresence.js";
import type * as functions_agentSchedules from "../functions/agentSchedules.js";
import type * as functions_ai from "../functions/ai.js";
import type * as functions_appointmentReports from "../functions/appointmentReports.js";
import type * as functions_appointmentWaitlist from "../functions/appointmentWaitlist.js";
import type * as functions_appointments from "../functions/appointments.js";
import type * as functions_archive from "../functions/archive.js";
import type * as functions_associationClaims from "../functions/associationClaims.js";
import type * as functions_associations from "../functions/associations.js";
import type * as functions_authRateLimit from "../functions/authRateLimit.js";
import type * as functions_autoDefense from "../functions/autoDefense.js";
import type * as functions_backgroundRemoval from "../functions/backgroundRemoval.js";
import type * as functions_callCenter from "../functions/callCenter.js";
import type * as functions_callLines from "../functions/callLines.js";
import type * as functions_callNotes from "../functions/callNotes.js";
import type * as functions_callRecordings from "../functions/callRecordings.js";
import type * as functions_cardDesigns from "../functions/cardDesigns.js";
import type * as functions_cardDesignsAI from "../functions/cardDesignsAI.js";
import type * as functions_chats from "../functions/chats.js";
import type * as functions_childProfiles from "../functions/childProfiles.js";
import type * as functions_citizenContacts from "../functions/citizenContacts.js";
import type * as functions_citizenContext from "../functions/citizenContext.js";
import type * as functions_communityEvents from "../functions/communityEvents.js";
import type * as functions_companies from "../functions/companies.js";
import type * as functions_consularCard from "../functions/consularCard.js";
import type * as functions_consularCardAttestation from "../functions/consularCardAttestation.js";
import type * as functions_consularNotifications from "../functions/consularNotifications.js";
import type * as functions_consularRegistrations from "../functions/consularRegistrations.js";
import type * as functions_contactSearch from "../functions/contactSearch.js";
import type * as functions_correspondance from "../functions/correspondance.js";
import type * as functions_correspondanceAnnotations from "../functions/correspondanceAnnotations.js";
import type * as functions_correspondanceConfig from "../functions/correspondanceConfig.js";
import type * as functions_correspondanceCore from "../functions/correspondanceCore.js";
import type * as functions_correspondanceDashboard from "../functions/correspondanceDashboard.js";
import type * as functions_correspondanceDocuments from "../functions/correspondanceDocuments.js";
import type * as functions_correspondanceEmail from "../functions/correspondanceEmail.js";
import type * as functions_correspondanceInbound from "../functions/correspondanceInbound.js";
import type * as functions_correspondanceInternalManifest from "../functions/correspondanceInternalManifest.js";
import type * as functions_correspondanceNetworkConfig from "../functions/correspondanceNetworkConfig.js";
import type * as functions_correspondanceNetworkStats from "../functions/correspondanceNetworkStats.js";
import type * as functions_correspondanceOcr from "../functions/correspondanceOcr.js";
import type * as functions_correspondancePdfGeneration from "../functions/correspondancePdfGeneration.js";
import type * as functions_correspondancePostalManifest from "../functions/correspondancePostalManifest.js";
import type * as functions_correspondancePostalManifestQueries from "../functions/correspondancePostalManifestQueries.js";
import type * as functions_correspondanceQualifiedSignature from "../functions/correspondanceQualifiedSignature.js";
import type * as functions_correspondanceSignature from "../functions/correspondanceSignature.js";
import type * as functions_correspondanceTransmissionBordereau from "../functions/correspondanceTransmissionBordereau.js";
import type * as functions_correspondanceWatermark from "../functions/correspondanceWatermark.js";
import type * as functions_cv from "../functions/cv.js";
import type * as functions_cvAI from "../functions/cvAI.js";
import type * as functions_deliveryPackages from "../functions/deliveryPackages.js";
import type * as functions_digitalMail from "../functions/digitalMail.js";
import type * as functions_diplomaticAffairs from "../functions/diplomaticAffairs.js";
import type * as functions_diplomaticFolders from "../functions/diplomaticFolders.js";
import type * as functions_diplomaticFoldersActions from "../functions/diplomaticFoldersActions.js";
import type * as functions_diplomaticProfile from "../functions/diplomaticProfile.js";
import type * as functions_documentFolders from "../functions/documentFolders.js";
import type * as functions_documentTemplates from "../functions/documentTemplates.js";
import type * as functions_documentVault from "../functions/documentVault.js";
import type * as functions_documentVerifications from "../functions/documentVerifications.js";
import type * as functions_documents from "../functions/documents.js";
import type * as functions_dossierProcedure from "../functions/dossierProcedure.js";
import type * as functions_draftMessages from "../functions/draftMessages.js";
import type * as functions_events from "../functions/events.js";
import type * as functions_faqs from "../functions/faqs.js";
import type * as functions_formTemplates from "../functions/formTemplates.js";
import type * as functions_gcpMonitoring from "../functions/gcpMonitoring.js";
import type * as functions_generatedDocuments from "../functions/generatedDocuments.js";
import type * as functions_generatedDocumentsData from "../functions/generatedDocumentsData.js";
import type * as functions_guides from "../functions/guides.js";
import type * as functions_iastedDocumentGeneration from "../functions/iastedDocumentGeneration.js";
import type * as functions_intelligence from "../functions/intelligence.js";
import type * as functions_intelligenceAlerts from "../functions/intelligenceAlerts.js";
import type * as functions_intelligenceBriefings from "../functions/intelligenceBriefings.js";
import type * as functions_intelligenceCases from "../functions/intelligenceCases.js";
import type * as functions_intelligenceGeoint from "../functions/intelligenceGeoint.js";
import type * as functions_intelligenceGraph from "../functions/intelligenceGraph.js";
import type * as functions_intelligenceLinks from "../functions/intelligenceLinks.js";
import type * as functions_intelligenceNotes from "../functions/intelligenceNotes.js";
import type * as functions_intelligenceTal from "../functions/intelligenceTal.js";
import type * as functions_intelligenceWatchlists from "../functions/intelligenceWatchlists.js";
import type * as functions_management from "../functions/management.js";
import type * as functions_meetings from "../functions/meetings.js";
import type * as functions_memberships from "../functions/memberships.js";
import type * as functions_messages from "../functions/messages.js";
import type * as functions_migrations from "../functions/migrations.js";
import type * as functions_ministry from "../functions/ministry.js";
import type * as functions_missedCalls from "../functions/missedCalls.js";
import type * as functions_newsletter from "../functions/newsletter.js";
import type * as functions_notifications from "../functions/notifications.js";
import type * as functions_orgCalendar from "../functions/orgCalendar.js";
import type * as functions_orgEscalationPolicy from "../functions/orgEscalationPolicy.js";
import type * as functions_orgIAstedConfig from "../functions/orgIAstedConfig.js";
import type * as functions_orgOverview from "../functions/orgOverview.js";
import type * as functions_orgRoleTemplates from "../functions/orgRoleTemplates.js";
import type * as functions_orgs from "../functions/orgs.js";
import type * as functions_orgsPublic from "../functions/orgsPublic.js";
import type * as functions_permissions from "../functions/permissions.js";
import type * as functions_pin from "../functions/pin.js";
import type * as functions_places from "../functions/places.js";
import type * as functions_posts from "../functions/posts.js";
import type * as functions_printJobs from "../functions/printJobs.js";
import type * as functions_profileNotes from "../functions/profileNotes.js";
import type * as functions_profiles from "../functions/profiles.js";
import type * as functions_publicServices from "../functions/publicServices.js";
import type * as functions_publicStats from "../functions/publicStats.js";
import type * as functions_pushSubscriptions from "../functions/pushSubscriptions.js";
import type * as functions_quickActions from "../functions/quickActions.js";
import type * as functions_releases from "../functions/releases.js";
import type * as functions_representations from "../functions/representations.js";
import type * as functions_requests from "../functions/requests.js";
import type * as functions_resources from "../functions/resources.js";
import type * as functions_ressourcesSeed from "../functions/ressourcesSeed.js";
import type * as functions_roleConfig from "../functions/roleConfig.js";
import type * as functions_security from "../functions/security.js";
import type * as functions_sendMail from "../functions/sendMail.js";
import type * as functions_seo from "../functions/seo.js";
import type * as functions_services from "../functions/services.js";
import type * as functions_servicesSeed from "../functions/servicesSeed.js";
import type * as functions_signatures from "../functions/signatures.js";
import type * as functions_slots from "../functions/slots.js";
import type * as functions_smsNotifications from "../functions/smsNotifications.js";
import type * as functions_statistics from "../functions/statistics.js";
import type * as functions_suggestions from "../functions/suggestions.js";
import type * as functions_supervision from "../functions/supervision.js";
import type * as functions_templateAI from "../functions/templateAI.js";
import type * as functions_templateApplicabilityMigration from "../functions/templateApplicabilityMigration.js";
import type * as functions_testSeeds from "../functions/testSeeds.js";
import type * as functions_tickets from "../functions/tickets.js";
import type * as functions_tutorialProgress from "../functions/tutorialProgress.js";
import type * as functions_tutorials from "../functions/tutorials.js";
import type * as functions_unifiedSearch from "../functions/unifiedSearch.js";
import type * as functions_userPreferences from "../functions/userPreferences.js";
import type * as functions_users from "../functions/users.js";
import type * as functions_voicemails from "../functions/voicemails.js";
import type * as functions_warehouse from "../functions/warehouse.js";
import type * as hippocampe from "../hippocampe.js";
import type * as http from "../http.js";
import type * as lib_aggregates from "../lib/aggregates.js";
import type * as lib_ai_gemini from "../lib/ai/gemini.js";
import type * as lib_applyOrgBranding from "../lib/applyOrgBranding.js";
import type * as lib_appointmentNotify from "../lib/appointmentNotify.js";
import type * as lib_archiveHelpers from "../lib/archiveHelpers.js";
import type * as lib_auth from "../lib/auth.js";
import type * as lib_bird from "../lib/bird.js";
import type * as lib_constants from "../lib/constants.js";
import type * as lib_correspondanceHelpers from "../lib/correspondanceHelpers.js";
import type * as lib_countryCodeValidator from "../lib/countryCodeValidator.js";
import type * as lib_customFunctions from "../lib/customFunctions.js";
import type * as lib_dbscan from "../lib/dbscan.js";
import type * as lib_diplomaticPipelineHelpers from "../lib/diplomaticPipelineHelpers.js";
import type * as lib_documentHelpers from "../lib/documentHelpers.js";
import type * as lib_documentPermissions from "../lib/documentPermissions.js";
import type * as lib_emailTemplates from "../lib/emailTemplates.js";
import type * as lib_encryption from "../lib/encryption.js";
import type * as lib_errors from "../lib/errors.js";
import type * as lib_generationTriggers from "../lib/generationTriggers.js";
import type * as lib_httpSecurity from "../lib/httpSecurity.js";
import type * as lib_iDocumentDefaultFolders from "../lib/iDocumentDefaultFolders.js";
import type * as lib_iastedLocales from "../lib/iastedLocales.js";
import type * as lib_ical from "../lib/ical.js";
import type * as lib_intelligenceAgencyVisibility from "../lib/intelligenceAgencyVisibility.js";
import type * as lib_intelligenceAudit from "../lib/intelligenceAudit.js";
import type * as lib_jsonRepair from "../lib/jsonRepair.js";
import type * as lib_legacyProfileToCardNumber from "../lib/legacyProfileToCardNumber.js";
import type * as lib_moduleCodes from "../lib/moduleCodes.js";
import type * as lib_neocortex from "../lib/neocortex.js";
import type * as lib_ocrProviders from "../lib/ocrProviders.js";
import type * as lib_orgHelpers from "../lib/orgHelpers.js";
import type * as lib_permissions from "../lib/permissions.js";
import type * as lib_phone from "../lib/phone.js";
import type * as lib_placeholderResolver from "../lib/placeholderResolver.js";
import type * as lib_platform from "../lib/platform.js";
import type * as lib_posthogEvents from "../lib/posthogEvents.js";
import type * as lib_projectDocHelpers from "../lib/projectDocHelpers.js";
import type * as lib_projectDocxGenerator from "../lib/projectDocxGenerator.js";
import type * as lib_projectPdfGenerator from "../lib/projectPdfGenerator.js";
import type * as lib_projectPptxGenerator from "../lib/projectPptxGenerator.js";
import type * as lib_qualifiedSignatureProviders from "../lib/qualifiedSignatureProviders.js";
import type * as lib_referenceHelpers from "../lib/referenceHelpers.js";
import type * as lib_registrationFormData from "../lib/registrationFormData.js";
import type * as lib_requestWorkflow from "../lib/requestWorkflow.js";
import type * as lib_roles from "../lib/roles.js";
import type * as lib_scheduleMatching from "../lib/scheduleMatching.js";
import type * as lib_startupChecks from "../lib/startupChecks.js";
import type * as lib_strategicSectors from "../lib/strategicSectors.js";
import type * as lib_taskCodes from "../lib/taskCodes.js";
import type * as lib_territoriality from "../lib/territoriality.js";
import type * as lib_triggerSetup from "../lib/triggerSetup.js";
import type * as lib_types from "../lib/types.js";
import type * as lib_userCategory from "../lib/userCategory.js";
import type * as lib_users from "../lib/users.js";
import type * as lib_utils from "../lib/utils.js";
import type * as lib_validators from "../lib/validators.js";
import type * as lib_warehouseAuth from "../lib/warehouseAuth.js";
import type * as limbique from "../limbique.js";
import type * as migrations_addAiAssistantModule from "../migrations/addAiAssistantModule.js";
import type * as migrations_addChatsAccessStandardThreadToHighRanks from "../migrations/addChatsAccessStandardThreadToHighRanks.js";
import type * as migrations_addDocumentsAiGenerationToHighRanks from "../migrations/addDocumentsAiGenerationToHighRanks.js";
import type * as migrations_addDocumentsTasksToHighRanks from "../migrations/addDocumentsTasksToHighRanks.js";
import type * as migrations_auditDocumentsAccessForHighRanks from "../migrations/auditDocumentsAccessForHighRanks.js";
import type * as migrations_backfillAggregates from "../migrations/backfillAggregates.js";
import type * as migrations_backfillArticlesGuidesI18n from "../migrations/backfillArticlesGuidesI18n.js";
import type * as migrations_backfillCopyOwnerOrgId from "../migrations/backfillCopyOwnerOrgId.js";
import type * as migrations_backfillEmptyFormData from "../migrations/backfillEmptyFormData.js";
import type * as migrations_backfillProfessionSkills from "../migrations/backfillProfessionSkills.js";
import type * as migrations_backfillProfileAttachment from "../migrations/backfillProfileAttachment.js";
import type * as migrations_backfillProfileCoordinates from "../migrations/backfillProfileCoordinates.js";
import type * as migrations_backfillRequestResidencePermit from "../migrations/backfillRequestResidencePermit.js";
import type * as migrations_backfillSkillsAggregates from "../migrations/backfillSkillsAggregates.js";
import type * as migrations_backfillTutorialStructure from "../migrations/backfillTutorialStructure.js";
import type * as migrations_cleanupPaymentsRefs from "../migrations/cleanupPaymentsRefs.js";
import type * as migrations_fixIdentityPhotos from "../migrations/fixIdentityPhotos.js";
import type * as migrations_fixOwnerIds from "../migrations/fixOwnerIds.js";
import type * as migrations_grantDocumentsAdminToHighRanks from "../migrations/grantDocumentsAdminToHighRanks.js";
import type * as migrations_initCardCounter from "../migrations/initCardCounter.js";
import type * as migrations_initCorrespondanceNetworkConfig from "../migrations/initCorrespondanceNetworkConfig.js";
import type * as migrations_migrateEmergencyContacts from "../migrations/migrateEmergencyContacts.js";
import type * as migrations_normalizePhones from "../migrations/normalizePhones.js";
import type * as migrations_renameDocumentFiles from "../migrations/renameDocumentFiles.js";
import type * as migrations_rollbackDocumentsAdminForHighRanks from "../migrations/rollbackDocumentsAdminForHighRanks.js";
import type * as migrations_seedDiplomaticTemplates from "../migrations/seedDiplomaticTemplates.js";
import type * as migrations_seedDiplomaticTemplatesData from "../migrations/seedDiplomaticTemplatesData.js";
import type * as migrations_syncCitizenProfilesViewTask from "../migrations/syncCitizenProfilesViewTask.js";
import type * as migrations_syncConsularNotificationSchema from "../migrations/syncConsularNotificationSchema.js";
import type * as monitoring from "../monitoring.js";
import type * as moteur from "../moteur.js";
import type * as plasticite from "../plasticite.js";
import type * as prefrontal from "../prefrontal.js";
import type * as restore_missing_docs from "../restore_missing_docs.js";
import type * as schemas_agentNotes from "../schemas/agentNotes.js";
import type * as schemas_agentPresence from "../schemas/agentPresence.js";
import type * as schemas_agentSchedules from "../schemas/agentSchedules.js";
import type * as schemas_aiActivityLog from "../schemas/aiActivityLog.js";
import type * as schemas_aiAgentPresence from "../schemas/aiAgentPresence.js";
import type * as schemas_aiCapabilityConfig from "../schemas/aiCapabilityConfig.js";
import type * as schemas_aiRealtimeSessions from "../schemas/aiRealtimeSessions.js";
import type * as schemas_aiSuggestions from "../schemas/aiSuggestions.js";
import type * as schemas_appointmentWaitlist from "../schemas/appointmentWaitlist.js";
import type * as schemas_appointments from "../schemas/appointments.js";
import type * as schemas_archivePolicies from "../schemas/archivePolicies.js";
import type * as schemas_associationClaims from "../schemas/associationClaims.js";
import type * as schemas_associationMembers from "../schemas/associationMembers.js";
import type * as schemas_associations from "../schemas/associations.js";
import type * as schemas_auditLog from "../schemas/auditLog.js";
import type * as schemas_callLines from "../schemas/callLines.js";
import type * as schemas_callNotes from "../schemas/callNotes.js";
import type * as schemas_callRecordings from "../schemas/callRecordings.js";
import type * as schemas_cardDesigns from "../schemas/cardDesigns.js";
import type * as schemas_chatMessages from "../schemas/chatMessages.js";
import type * as schemas_chatTyping from "../schemas/chatTyping.js";
import type * as schemas_chats from "../schemas/chats.js";
import type * as schemas_childProfiles from "../schemas/childProfiles.js";
import type * as schemas_communityEvents from "../schemas/communityEvents.js";
import type * as schemas_companies from "../schemas/companies.js";
import type * as schemas_companyMembers from "../schemas/companyMembers.js";
import type * as schemas_consularNotifications from "../schemas/consularNotifications.js";
import type * as schemas_consularRegistrations from "../schemas/consularRegistrations.js";
import type * as schemas_conversations from "../schemas/conversations.js";
import type * as schemas_correspondance from "../schemas/correspondance.js";
import type * as schemas_correspondanceNetworkConfig from "../schemas/correspondanceNetworkConfig.js";
import type * as schemas_counters from "../schemas/counters.js";
import type * as schemas_cv from "../schemas/cv.js";
import type * as schemas_deliveryPackages from "../schemas/deliveryPackages.js";
import type * as schemas_digitalMail from "../schemas/digitalMail.js";
import type * as schemas_diplomaticAffairs from "../schemas/diplomaticAffairs.js";
import type * as schemas_documentTemplateVersions from "../schemas/documentTemplateVersions.js";
import type * as schemas_documentTemplates from "../schemas/documentTemplates.js";
import type * as schemas_documentVerifications from "../schemas/documentVerifications.js";
import type * as schemas_documents from "../schemas/documents.js";
import type * as schemas_dossierProcedure from "../schemas/dossierProcedure.js";
import type * as schemas_draftMessages from "../schemas/draftMessages.js";
import type * as schemas_events from "../schemas/events.js";
import type * as schemas_faqs from "../schemas/faqs.js";
import type * as schemas_formTemplates from "../schemas/formTemplates.js";
import type * as schemas_gcpMetricsCache from "../schemas/gcpMetricsCache.js";
import type * as schemas_generatedDocuments from "../schemas/generatedDocuments.js";
import type * as schemas_guides from "../schemas/guides.js";
import type * as schemas_iastedConversations from "../schemas/iastedConversations.js";
import type * as schemas_iastedDevicePresence from "../schemas/iastedDevicePresence.js";
import type * as schemas_iastedKnowledge from "../schemas/iastedKnowledge.js";
import type * as schemas_iastedMemories from "../schemas/iastedMemories.js";
import type * as schemas_iastedUserLexicon from "../schemas/iastedUserLexicon.js";
import type * as schemas_index from "../schemas/index.js";
import type * as schemas_intelligenceAlerts from "../schemas/intelligenceAlerts.js";
import type * as schemas_intelligenceAuditLog from "../schemas/intelligenceAuditLog.js";
import type * as schemas_intelligenceBriefings from "../schemas/intelligenceBriefings.js";
import type * as schemas_intelligenceCases from "../schemas/intelligenceCases.js";
import type * as schemas_intelligenceEnclaves from "../schemas/intelligenceEnclaves.js";
import type * as schemas_intelligenceLinks from "../schemas/intelligenceLinks.js";
import type * as schemas_intelligenceNotes from "../schemas/intelligenceNotes.js";
import type * as schemas_intelligenceWatchlists from "../schemas/intelligenceWatchlists.js";
import type * as schemas_ipThreatScores from "../schemas/ipThreatScores.js";
import type * as schemas_meetings from "../schemas/meetings.js";
import type * as schemas_memberships from "../schemas/memberships.js";
import type * as schemas_messages from "../schemas/messages.js";
import type * as schemas_missedCalls from "../schemas/missedCalls.js";
import type * as schemas_neocortex from "../schemas/neocortex.js";
import type * as schemas_newsletterSubscriptions from "../schemas/newsletterSubscriptions.js";
import type * as schemas_notifications from "../schemas/notifications.js";
import type * as schemas_orgCalendar from "../schemas/orgCalendar.js";
import type * as schemas_orgEscalationPolicy from "../schemas/orgEscalationPolicy.js";
import type * as schemas_orgIAstedConfig from "../schemas/orgIAstedConfig.js";
import type * as schemas_orgPublicDocuments from "../schemas/orgPublicDocuments.js";
import type * as schemas_orgRoleTemplates from "../schemas/orgRoleTemplates.js";
import type * as schemas_orgServices from "../schemas/orgServices.js";
import type * as schemas_orgs from "../schemas/orgs.js";
import type * as schemas_posts from "../schemas/posts.js";
import type * as schemas_printJobs from "../schemas/printJobs.js";
import type * as schemas_profileNotes from "../schemas/profileNotes.js";
import type * as schemas_profiles from "../schemas/profiles.js";
import type * as schemas_pushSubscriptions from "../schemas/pushSubscriptions.js";
import type * as schemas_requests from "../schemas/requests.js";
import type * as schemas_roleConfig from "../schemas/roleConfig.js";
import type * as schemas_security from "../schemas/security.js";
import type * as schemas_services from "../schemas/services.js";
import type * as schemas_skillsAggregation from "../schemas/skillsAggregation.js";
import type * as schemas_streamingChats from "../schemas/streamingChats.js";
import type * as schemas_supervisionSessions from "../schemas/supervisionSessions.js";
import type * as schemas_tickets from "../schemas/tickets.js";
import type * as schemas_tutorialProgress from "../schemas/tutorialProgress.js";
import type * as schemas_tutorials from "../schemas/tutorials.js";
import type * as schemas_userAIPreferences from "../schemas/userAIPreferences.js";
import type * as schemas_userIastedVoicePrefs from "../schemas/userIastedVoicePrefs.js";
import type * as schemas_userVoicePrints from "../schemas/userVoicePrints.js";
import type * as schemas_users from "../schemas/users.js";
import type * as schemas_voicemails from "../schemas/voicemails.js";
import type * as seedWorld from "../seedWorld.js";
import type * as seeds_associations from "../seeds/associations.js";
import type * as seeds_clearAll from "../seeds/clearAll.js";
import type * as seeds_declarationServices from "../seeds/declarationServices.js";
import type * as seeds_diplomatic_network from "../seeds/diplomatic_network.js";
import type * as seeds_diplomatic_network_dev from "../seeds/diplomatic_network_dev.js";
import type * as seeds_diplomatic_network_espagne from "../seeds/diplomatic_network_espagne.js";
import type * as seeds_guides_world from "../seeds/guides_world.js";
import type * as seeds_listDevAccounts from "../seeds/listDevAccounts.js";
import type * as seeds_listOrgStaff from "../seeds/listOrgStaff.js";
import type * as seeds_roles from "../seeds/roles.js";
import type * as seeds_seedDevAuthUsers from "../seeds/seedDevAuthUsers.js";
import type * as seeds_seedDevCitizenProfiles from "../seeds/seedDevCitizenProfiles.js";
import type * as seeds_seedFromJson from "../seeds/seedFromJson.js";
import type * as seeds_seedOrgDetails from "../seeds/seedOrgDetails.js";
import type * as seeds_seedOrgPublicDocs from "../seeds/seedOrgPublicDocs.js";
import type * as seeds_seedPosts from "../seeds/seedPosts.js";
import type * as seeds_seedShowcaseArticle from "../seeds/seedShowcaseArticle.js";
import type * as seeds_seedUsers from "../seeds/seedUsers.js";
import type * as seeds_serviceFormSchemas from "../seeds/serviceFormSchemas.js";
import type * as seeds_staffAccounts from "../seeds/staffAccounts.js";
import type * as seeds_tutorials from "../seeds/tutorials.js";
import type * as sensoriel from "../sensoriel.js";
import type * as testDumpRecords from "../testDumpRecords.js";
import type * as testQuery from "../testQuery.js";
import type * as testUser from "../testUser.js";
import type * as triggers_index from "../triggers/index.js";
import type * as triggers_skillsAggregation from "../triggers/skillsAggregation.js";
import type * as visuel from "../visuel.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  "actions/gcpMonitoring": typeof actions_gcpMonitoring;
  "actions/iAstedPromptGenerator": typeof actions_iAstedPromptGenerator;
  "actions/intelligenceBriefings": typeof actions_intelligenceBriefings;
  "actions/livekit": typeof actions_livekit;
  "actions/posthog": typeof actions_posthog;
  "actions/posthogHealthCheck": typeof actions_posthogHealthCheck;
  "actions/push": typeof actions_push;
  "ai/activityLog": typeof ai_activityLog;
  "ai/adminChat": typeof ai_adminChat;
  "ai/adminChatStreaming": typeof ai_adminChatStreaming;
  "ai/adminContext": typeof ai_adminContext;
  "ai/adminToolExecutor": typeof ai_adminToolExecutor;
  "ai/adminTools": typeof ai_adminTools;
  "ai/adminVoice": typeof ai_adminVoice;
  "ai/aiTriggers": typeof ai_aiTriggers;
  "ai/assets/idPhotoGuide": typeof ai_assets_idPhotoGuide;
  "ai/capabilities/_types": typeof ai_capabilities__types;
  "ai/capabilities/autoSummary": typeof ai_capabilities_autoSummary;
  "ai/capabilities/bulkActionsHelper": typeof ai_capabilities_bulkActionsHelper;
  "ai/capabilities/complianceCheck": typeof ai_capabilities_complianceCheck;
  "ai/capabilities/correspondanceDrafting": typeof ai_capabilities_correspondanceDrafting;
  "ai/capabilities/documentAnalysis": typeof ai_capabilities_documentAnalysis;
  "ai/capabilities/documentDrafting": typeof ai_capabilities_documentDrafting;
  "ai/capabilities/meetingPrep": typeof ai_capabilities_meetingPrep;
  "ai/capabilities/nextStepSuggestion": typeof ai_capabilities_nextStepSuggestion;
  "ai/capabilities/proactiveNotifications": typeof ai_capabilities_proactiveNotifications;
  "ai/capabilities/requestTriage": typeof ai_capabilities_requestTriage;
  "ai/capabilities/riskDetection": typeof ai_capabilities_riskDetection;
  "ai/capabilities/voiceAssist": typeof ai_capabilities_voiceAssist;
  "ai/capabilitiesData": typeof ai_capabilitiesData;
  "ai/capabilityRegistry": typeof ai_capabilityRegistry;
  "ai/chat": typeof ai_chat;
  "ai/contextStore": typeof ai_contextStore;
  "ai/dashboardAI": typeof ai_dashboardAI;
  "ai/diplomaticAI": typeof ai_diplomaticAI;
  "ai/dispatcher": typeof ai_dispatcher;
  "ai/documentAnalysis": typeof ai_documentAnalysis;
  "ai/documentExtraction": typeof ai_documentExtraction;
  "ai/iastedConversations": typeof ai_iastedConversations;
  "ai/iastedDelegationHelpers": typeof ai_iastedDelegationHelpers;
  "ai/iastedDevicePresence": typeof ai_iastedDevicePresence;
  "ai/iastedMeetingSummariesHelpers": typeof ai_iastedMeetingSummariesHelpers;
  "ai/iastedMemories": typeof ai_iastedMemories;
  "ai/iastedPatternMining": typeof ai_iastedPatternMining;
  "ai/iastedRealtimePrompt": typeof ai_iastedRealtimePrompt;
  "ai/mrRay": typeof ai_mrRay;
  "ai/preferences": typeof ai_preferences;
  "ai/proactiveAgent": typeof ai_proactiveAgent;
  "ai/proactiveRouter": typeof ai_proactiveRouter;
  "ai/providers/anthropic": typeof ai_providers_anthropic;
  "ai/providers/gemini": typeof ai_providers_gemini;
  "ai/publicChat": typeof ai_publicChat;
  "ai/rag/embeddingService": typeof ai_rag_embeddingService;
  "ai/rag/indexer": typeof ai_rag_indexer;
  "ai/rag/retriever": typeof ai_rag_retriever;
  "ai/rateLimiter": typeof ai_rateLimiter;
  "ai/realtimeAvailable": typeof ai_realtimeAvailable;
  "ai/realtimeKnowledge": typeof ai_realtimeKnowledge;
  "ai/realtimeSessions": typeof ai_realtimeSessions;
  "ai/realtimeToken": typeof ai_realtimeToken;
  "ai/realtimeToolExecutor": typeof ai_realtimeToolExecutor;
  "ai/realtimeTools": typeof ai_realtimeTools;
  "ai/realtimeTypes": typeof ai_realtimeTypes;
  "ai/routes_manifest": typeof ai_routes_manifest;
  "ai/scheduledSweeper": typeof ai_scheduledSweeper;
  "ai/securityGuardian": typeof ai_securityGuardian;
  "ai/streamingChats": typeof ai_streamingChats;
  "ai/suggestions": typeof ai_suggestions;
  "ai/tools": typeof ai_tools;
  "ai/userIdentity": typeof ai_userIdentity;
  "ai/userLexicon": typeof ai_userLexicon;
  "ai/vision": typeof ai_vision;
  "ai/voice": typeof ai_voice;
  "ai/voicePreferences": typeof ai_voicePreferences;
  "ai/voicePrints": typeof ai_voicePrints;
  "assets/sceauGabonBase64": typeof assets_sceauGabonBase64;
  auditif: typeof auditif;
  "betterAuth/auth": typeof betterAuth_auth;
  crons: typeof crons;
  "crons/archiveExpiration": typeof crons_archiveExpiration;
  "crons/correspondanceSla": typeof crons_correspondanceSla;
  "crons/expiration": typeof crons_expiration;
  "crons/posthogHealthCheck": typeof crons_posthogHealthCheck;
  "functions/admin": typeof functions_admin;
  "functions/adminSkills": typeof functions_adminSkills;
  "functions/adminSkillsActions": typeof functions_adminSkillsActions;
  "functions/agentNotes": typeof functions_agentNotes;
  "functions/agentPresence": typeof functions_agentPresence;
  "functions/agentSchedules": typeof functions_agentSchedules;
  "functions/ai": typeof functions_ai;
  "functions/appointmentReports": typeof functions_appointmentReports;
  "functions/appointmentWaitlist": typeof functions_appointmentWaitlist;
  "functions/appointments": typeof functions_appointments;
  "functions/archive": typeof functions_archive;
  "functions/associationClaims": typeof functions_associationClaims;
  "functions/associations": typeof functions_associations;
  "functions/authRateLimit": typeof functions_authRateLimit;
  "functions/autoDefense": typeof functions_autoDefense;
  "functions/backgroundRemoval": typeof functions_backgroundRemoval;
  "functions/callCenter": typeof functions_callCenter;
  "functions/callLines": typeof functions_callLines;
  "functions/callNotes": typeof functions_callNotes;
  "functions/callRecordings": typeof functions_callRecordings;
  "functions/cardDesigns": typeof functions_cardDesigns;
  "functions/cardDesignsAI": typeof functions_cardDesignsAI;
  "functions/chats": typeof functions_chats;
  "functions/childProfiles": typeof functions_childProfiles;
  "functions/citizenContacts": typeof functions_citizenContacts;
  "functions/citizenContext": typeof functions_citizenContext;
  "functions/communityEvents": typeof functions_communityEvents;
  "functions/companies": typeof functions_companies;
  "functions/consularCard": typeof functions_consularCard;
  "functions/consularCardAttestation": typeof functions_consularCardAttestation;
  "functions/consularNotifications": typeof functions_consularNotifications;
  "functions/consularRegistrations": typeof functions_consularRegistrations;
  "functions/contactSearch": typeof functions_contactSearch;
  "functions/correspondance": typeof functions_correspondance;
  "functions/correspondanceAnnotations": typeof functions_correspondanceAnnotations;
  "functions/correspondanceConfig": typeof functions_correspondanceConfig;
  "functions/correspondanceCore": typeof functions_correspondanceCore;
  "functions/correspondanceDashboard": typeof functions_correspondanceDashboard;
  "functions/correspondanceDocuments": typeof functions_correspondanceDocuments;
  "functions/correspondanceEmail": typeof functions_correspondanceEmail;
  "functions/correspondanceInbound": typeof functions_correspondanceInbound;
  "functions/correspondanceInternalManifest": typeof functions_correspondanceInternalManifest;
  "functions/correspondanceNetworkConfig": typeof functions_correspondanceNetworkConfig;
  "functions/correspondanceNetworkStats": typeof functions_correspondanceNetworkStats;
  "functions/correspondanceOcr": typeof functions_correspondanceOcr;
  "functions/correspondancePdfGeneration": typeof functions_correspondancePdfGeneration;
  "functions/correspondancePostalManifest": typeof functions_correspondancePostalManifest;
  "functions/correspondancePostalManifestQueries": typeof functions_correspondancePostalManifestQueries;
  "functions/correspondanceQualifiedSignature": typeof functions_correspondanceQualifiedSignature;
  "functions/correspondanceSignature": typeof functions_correspondanceSignature;
  "functions/correspondanceTransmissionBordereau": typeof functions_correspondanceTransmissionBordereau;
  "functions/correspondanceWatermark": typeof functions_correspondanceWatermark;
  "functions/cv": typeof functions_cv;
  "functions/cvAI": typeof functions_cvAI;
  "functions/deliveryPackages": typeof functions_deliveryPackages;
  "functions/digitalMail": typeof functions_digitalMail;
  "functions/diplomaticAffairs": typeof functions_diplomaticAffairs;
  "functions/diplomaticFolders": typeof functions_diplomaticFolders;
  "functions/diplomaticFoldersActions": typeof functions_diplomaticFoldersActions;
  "functions/diplomaticProfile": typeof functions_diplomaticProfile;
  "functions/documentFolders": typeof functions_documentFolders;
  "functions/documentTemplates": typeof functions_documentTemplates;
  "functions/documentVault": typeof functions_documentVault;
  "functions/documentVerifications": typeof functions_documentVerifications;
  "functions/documents": typeof functions_documents;
  "functions/dossierProcedure": typeof functions_dossierProcedure;
  "functions/draftMessages": typeof functions_draftMessages;
  "functions/events": typeof functions_events;
  "functions/faqs": typeof functions_faqs;
  "functions/formTemplates": typeof functions_formTemplates;
  "functions/gcpMonitoring": typeof functions_gcpMonitoring;
  "functions/generatedDocuments": typeof functions_generatedDocuments;
  "functions/generatedDocumentsData": typeof functions_generatedDocumentsData;
  "functions/guides": typeof functions_guides;
  "functions/iastedDocumentGeneration": typeof functions_iastedDocumentGeneration;
  "functions/intelligence": typeof functions_intelligence;
  "functions/intelligenceAlerts": typeof functions_intelligenceAlerts;
  "functions/intelligenceBriefings": typeof functions_intelligenceBriefings;
  "functions/intelligenceCases": typeof functions_intelligenceCases;
  "functions/intelligenceGeoint": typeof functions_intelligenceGeoint;
  "functions/intelligenceGraph": typeof functions_intelligenceGraph;
  "functions/intelligenceLinks": typeof functions_intelligenceLinks;
  "functions/intelligenceNotes": typeof functions_intelligenceNotes;
  "functions/intelligenceTal": typeof functions_intelligenceTal;
  "functions/intelligenceWatchlists": typeof functions_intelligenceWatchlists;
  "functions/management": typeof functions_management;
  "functions/meetings": typeof functions_meetings;
  "functions/memberships": typeof functions_memberships;
  "functions/messages": typeof functions_messages;
  "functions/migrations": typeof functions_migrations;
  "functions/ministry": typeof functions_ministry;
  "functions/missedCalls": typeof functions_missedCalls;
  "functions/newsletter": typeof functions_newsletter;
  "functions/notifications": typeof functions_notifications;
  "functions/orgCalendar": typeof functions_orgCalendar;
  "functions/orgEscalationPolicy": typeof functions_orgEscalationPolicy;
  "functions/orgIAstedConfig": typeof functions_orgIAstedConfig;
  "functions/orgOverview": typeof functions_orgOverview;
  "functions/orgRoleTemplates": typeof functions_orgRoleTemplates;
  "functions/orgs": typeof functions_orgs;
  "functions/orgsPublic": typeof functions_orgsPublic;
  "functions/permissions": typeof functions_permissions;
  "functions/pin": typeof functions_pin;
  "functions/places": typeof functions_places;
  "functions/posts": typeof functions_posts;
  "functions/printJobs": typeof functions_printJobs;
  "functions/profileNotes": typeof functions_profileNotes;
  "functions/profiles": typeof functions_profiles;
  "functions/publicServices": typeof functions_publicServices;
  "functions/publicStats": typeof functions_publicStats;
  "functions/pushSubscriptions": typeof functions_pushSubscriptions;
  "functions/quickActions": typeof functions_quickActions;
  "functions/releases": typeof functions_releases;
  "functions/representations": typeof functions_representations;
  "functions/requests": typeof functions_requests;
  "functions/resources": typeof functions_resources;
  "functions/ressourcesSeed": typeof functions_ressourcesSeed;
  "functions/roleConfig": typeof functions_roleConfig;
  "functions/security": typeof functions_security;
  "functions/sendMail": typeof functions_sendMail;
  "functions/seo": typeof functions_seo;
  "functions/services": typeof functions_services;
  "functions/servicesSeed": typeof functions_servicesSeed;
  "functions/signatures": typeof functions_signatures;
  "functions/slots": typeof functions_slots;
  "functions/smsNotifications": typeof functions_smsNotifications;
  "functions/statistics": typeof functions_statistics;
  "functions/suggestions": typeof functions_suggestions;
  "functions/supervision": typeof functions_supervision;
  "functions/templateAI": typeof functions_templateAI;
  "functions/templateApplicabilityMigration": typeof functions_templateApplicabilityMigration;
  "functions/testSeeds": typeof functions_testSeeds;
  "functions/tickets": typeof functions_tickets;
  "functions/tutorialProgress": typeof functions_tutorialProgress;
  "functions/tutorials": typeof functions_tutorials;
  "functions/unifiedSearch": typeof functions_unifiedSearch;
  "functions/userPreferences": typeof functions_userPreferences;
  "functions/users": typeof functions_users;
  "functions/voicemails": typeof functions_voicemails;
  "functions/warehouse": typeof functions_warehouse;
  hippocampe: typeof hippocampe;
  http: typeof http;
  "lib/aggregates": typeof lib_aggregates;
  "lib/ai/gemini": typeof lib_ai_gemini;
  "lib/applyOrgBranding": typeof lib_applyOrgBranding;
  "lib/appointmentNotify": typeof lib_appointmentNotify;
  "lib/archiveHelpers": typeof lib_archiveHelpers;
  "lib/auth": typeof lib_auth;
  "lib/bird": typeof lib_bird;
  "lib/constants": typeof lib_constants;
  "lib/correspondanceHelpers": typeof lib_correspondanceHelpers;
  "lib/countryCodeValidator": typeof lib_countryCodeValidator;
  "lib/customFunctions": typeof lib_customFunctions;
  "lib/dbscan": typeof lib_dbscan;
  "lib/diplomaticPipelineHelpers": typeof lib_diplomaticPipelineHelpers;
  "lib/documentHelpers": typeof lib_documentHelpers;
  "lib/documentPermissions": typeof lib_documentPermissions;
  "lib/emailTemplates": typeof lib_emailTemplates;
  "lib/encryption": typeof lib_encryption;
  "lib/errors": typeof lib_errors;
  "lib/generationTriggers": typeof lib_generationTriggers;
  "lib/httpSecurity": typeof lib_httpSecurity;
  "lib/iDocumentDefaultFolders": typeof lib_iDocumentDefaultFolders;
  "lib/iastedLocales": typeof lib_iastedLocales;
  "lib/ical": typeof lib_ical;
  "lib/intelligenceAgencyVisibility": typeof lib_intelligenceAgencyVisibility;
  "lib/intelligenceAudit": typeof lib_intelligenceAudit;
  "lib/jsonRepair": typeof lib_jsonRepair;
  "lib/legacyProfileToCardNumber": typeof lib_legacyProfileToCardNumber;
  "lib/moduleCodes": typeof lib_moduleCodes;
  "lib/neocortex": typeof lib_neocortex;
  "lib/ocrProviders": typeof lib_ocrProviders;
  "lib/orgHelpers": typeof lib_orgHelpers;
  "lib/permissions": typeof lib_permissions;
  "lib/phone": typeof lib_phone;
  "lib/placeholderResolver": typeof lib_placeholderResolver;
  "lib/platform": typeof lib_platform;
  "lib/posthogEvents": typeof lib_posthogEvents;
  "lib/projectDocHelpers": typeof lib_projectDocHelpers;
  "lib/projectDocxGenerator": typeof lib_projectDocxGenerator;
  "lib/projectPdfGenerator": typeof lib_projectPdfGenerator;
  "lib/projectPptxGenerator": typeof lib_projectPptxGenerator;
  "lib/qualifiedSignatureProviders": typeof lib_qualifiedSignatureProviders;
  "lib/referenceHelpers": typeof lib_referenceHelpers;
  "lib/registrationFormData": typeof lib_registrationFormData;
  "lib/requestWorkflow": typeof lib_requestWorkflow;
  "lib/roles": typeof lib_roles;
  "lib/scheduleMatching": typeof lib_scheduleMatching;
  "lib/startupChecks": typeof lib_startupChecks;
  "lib/strategicSectors": typeof lib_strategicSectors;
  "lib/taskCodes": typeof lib_taskCodes;
  "lib/territoriality": typeof lib_territoriality;
  "lib/triggerSetup": typeof lib_triggerSetup;
  "lib/types": typeof lib_types;
  "lib/userCategory": typeof lib_userCategory;
  "lib/users": typeof lib_users;
  "lib/utils": typeof lib_utils;
  "lib/validators": typeof lib_validators;
  "lib/warehouseAuth": typeof lib_warehouseAuth;
  limbique: typeof limbique;
  "migrations/addAiAssistantModule": typeof migrations_addAiAssistantModule;
  "migrations/addChatsAccessStandardThreadToHighRanks": typeof migrations_addChatsAccessStandardThreadToHighRanks;
  "migrations/addDocumentsAiGenerationToHighRanks": typeof migrations_addDocumentsAiGenerationToHighRanks;
  "migrations/addDocumentsTasksToHighRanks": typeof migrations_addDocumentsTasksToHighRanks;
  "migrations/auditDocumentsAccessForHighRanks": typeof migrations_auditDocumentsAccessForHighRanks;
  "migrations/backfillAggregates": typeof migrations_backfillAggregates;
  "migrations/backfillArticlesGuidesI18n": typeof migrations_backfillArticlesGuidesI18n;
  "migrations/backfillCopyOwnerOrgId": typeof migrations_backfillCopyOwnerOrgId;
  "migrations/backfillEmptyFormData": typeof migrations_backfillEmptyFormData;
  "migrations/backfillProfessionSkills": typeof migrations_backfillProfessionSkills;
  "migrations/backfillProfileAttachment": typeof migrations_backfillProfileAttachment;
  "migrations/backfillProfileCoordinates": typeof migrations_backfillProfileCoordinates;
  "migrations/backfillRequestResidencePermit": typeof migrations_backfillRequestResidencePermit;
  "migrations/backfillSkillsAggregates": typeof migrations_backfillSkillsAggregates;
  "migrations/backfillTutorialStructure": typeof migrations_backfillTutorialStructure;
  "migrations/cleanupPaymentsRefs": typeof migrations_cleanupPaymentsRefs;
  "migrations/fixIdentityPhotos": typeof migrations_fixIdentityPhotos;
  "migrations/fixOwnerIds": typeof migrations_fixOwnerIds;
  "migrations/grantDocumentsAdminToHighRanks": typeof migrations_grantDocumentsAdminToHighRanks;
  "migrations/initCardCounter": typeof migrations_initCardCounter;
  "migrations/initCorrespondanceNetworkConfig": typeof migrations_initCorrespondanceNetworkConfig;
  "migrations/migrateEmergencyContacts": typeof migrations_migrateEmergencyContacts;
  "migrations/normalizePhones": typeof migrations_normalizePhones;
  "migrations/renameDocumentFiles": typeof migrations_renameDocumentFiles;
  "migrations/rollbackDocumentsAdminForHighRanks": typeof migrations_rollbackDocumentsAdminForHighRanks;
  "migrations/seedDiplomaticTemplates": typeof migrations_seedDiplomaticTemplates;
  "migrations/seedDiplomaticTemplatesData": typeof migrations_seedDiplomaticTemplatesData;
  "migrations/syncCitizenProfilesViewTask": typeof migrations_syncCitizenProfilesViewTask;
  "migrations/syncConsularNotificationSchema": typeof migrations_syncConsularNotificationSchema;
  monitoring: typeof monitoring;
  moteur: typeof moteur;
  plasticite: typeof plasticite;
  prefrontal: typeof prefrontal;
  restore_missing_docs: typeof restore_missing_docs;
  "schemas/agentNotes": typeof schemas_agentNotes;
  "schemas/agentPresence": typeof schemas_agentPresence;
  "schemas/agentSchedules": typeof schemas_agentSchedules;
  "schemas/aiActivityLog": typeof schemas_aiActivityLog;
  "schemas/aiAgentPresence": typeof schemas_aiAgentPresence;
  "schemas/aiCapabilityConfig": typeof schemas_aiCapabilityConfig;
  "schemas/aiRealtimeSessions": typeof schemas_aiRealtimeSessions;
  "schemas/aiSuggestions": typeof schemas_aiSuggestions;
  "schemas/appointmentWaitlist": typeof schemas_appointmentWaitlist;
  "schemas/appointments": typeof schemas_appointments;
  "schemas/archivePolicies": typeof schemas_archivePolicies;
  "schemas/associationClaims": typeof schemas_associationClaims;
  "schemas/associationMembers": typeof schemas_associationMembers;
  "schemas/associations": typeof schemas_associations;
  "schemas/auditLog": typeof schemas_auditLog;
  "schemas/callLines": typeof schemas_callLines;
  "schemas/callNotes": typeof schemas_callNotes;
  "schemas/callRecordings": typeof schemas_callRecordings;
  "schemas/cardDesigns": typeof schemas_cardDesigns;
  "schemas/chatMessages": typeof schemas_chatMessages;
  "schemas/chatTyping": typeof schemas_chatTyping;
  "schemas/chats": typeof schemas_chats;
  "schemas/childProfiles": typeof schemas_childProfiles;
  "schemas/communityEvents": typeof schemas_communityEvents;
  "schemas/companies": typeof schemas_companies;
  "schemas/companyMembers": typeof schemas_companyMembers;
  "schemas/consularNotifications": typeof schemas_consularNotifications;
  "schemas/consularRegistrations": typeof schemas_consularRegistrations;
  "schemas/conversations": typeof schemas_conversations;
  "schemas/correspondance": typeof schemas_correspondance;
  "schemas/correspondanceNetworkConfig": typeof schemas_correspondanceNetworkConfig;
  "schemas/counters": typeof schemas_counters;
  "schemas/cv": typeof schemas_cv;
  "schemas/deliveryPackages": typeof schemas_deliveryPackages;
  "schemas/digitalMail": typeof schemas_digitalMail;
  "schemas/diplomaticAffairs": typeof schemas_diplomaticAffairs;
  "schemas/documentTemplateVersions": typeof schemas_documentTemplateVersions;
  "schemas/documentTemplates": typeof schemas_documentTemplates;
  "schemas/documentVerifications": typeof schemas_documentVerifications;
  "schemas/documents": typeof schemas_documents;
  "schemas/dossierProcedure": typeof schemas_dossierProcedure;
  "schemas/draftMessages": typeof schemas_draftMessages;
  "schemas/events": typeof schemas_events;
  "schemas/faqs": typeof schemas_faqs;
  "schemas/formTemplates": typeof schemas_formTemplates;
  "schemas/gcpMetricsCache": typeof schemas_gcpMetricsCache;
  "schemas/generatedDocuments": typeof schemas_generatedDocuments;
  "schemas/guides": typeof schemas_guides;
  "schemas/iastedConversations": typeof schemas_iastedConversations;
  "schemas/iastedDevicePresence": typeof schemas_iastedDevicePresence;
  "schemas/iastedKnowledge": typeof schemas_iastedKnowledge;
  "schemas/iastedMemories": typeof schemas_iastedMemories;
  "schemas/iastedUserLexicon": typeof schemas_iastedUserLexicon;
  "schemas/index": typeof schemas_index;
  "schemas/intelligenceAlerts": typeof schemas_intelligenceAlerts;
  "schemas/intelligenceAuditLog": typeof schemas_intelligenceAuditLog;
  "schemas/intelligenceBriefings": typeof schemas_intelligenceBriefings;
  "schemas/intelligenceCases": typeof schemas_intelligenceCases;
  "schemas/intelligenceEnclaves": typeof schemas_intelligenceEnclaves;
  "schemas/intelligenceLinks": typeof schemas_intelligenceLinks;
  "schemas/intelligenceNotes": typeof schemas_intelligenceNotes;
  "schemas/intelligenceWatchlists": typeof schemas_intelligenceWatchlists;
  "schemas/ipThreatScores": typeof schemas_ipThreatScores;
  "schemas/meetings": typeof schemas_meetings;
  "schemas/memberships": typeof schemas_memberships;
  "schemas/messages": typeof schemas_messages;
  "schemas/missedCalls": typeof schemas_missedCalls;
  "schemas/neocortex": typeof schemas_neocortex;
  "schemas/newsletterSubscriptions": typeof schemas_newsletterSubscriptions;
  "schemas/notifications": typeof schemas_notifications;
  "schemas/orgCalendar": typeof schemas_orgCalendar;
  "schemas/orgEscalationPolicy": typeof schemas_orgEscalationPolicy;
  "schemas/orgIAstedConfig": typeof schemas_orgIAstedConfig;
  "schemas/orgPublicDocuments": typeof schemas_orgPublicDocuments;
  "schemas/orgRoleTemplates": typeof schemas_orgRoleTemplates;
  "schemas/orgServices": typeof schemas_orgServices;
  "schemas/orgs": typeof schemas_orgs;
  "schemas/posts": typeof schemas_posts;
  "schemas/printJobs": typeof schemas_printJobs;
  "schemas/profileNotes": typeof schemas_profileNotes;
  "schemas/profiles": typeof schemas_profiles;
  "schemas/pushSubscriptions": typeof schemas_pushSubscriptions;
  "schemas/requests": typeof schemas_requests;
  "schemas/roleConfig": typeof schemas_roleConfig;
  "schemas/security": typeof schemas_security;
  "schemas/services": typeof schemas_services;
  "schemas/skillsAggregation": typeof schemas_skillsAggregation;
  "schemas/streamingChats": typeof schemas_streamingChats;
  "schemas/supervisionSessions": typeof schemas_supervisionSessions;
  "schemas/tickets": typeof schemas_tickets;
  "schemas/tutorialProgress": typeof schemas_tutorialProgress;
  "schemas/tutorials": typeof schemas_tutorials;
  "schemas/userAIPreferences": typeof schemas_userAIPreferences;
  "schemas/userIastedVoicePrefs": typeof schemas_userIastedVoicePrefs;
  "schemas/userVoicePrints": typeof schemas_userVoicePrints;
  "schemas/users": typeof schemas_users;
  "schemas/voicemails": typeof schemas_voicemails;
  seedWorld: typeof seedWorld;
  "seeds/associations": typeof seeds_associations;
  "seeds/clearAll": typeof seeds_clearAll;
  "seeds/declarationServices": typeof seeds_declarationServices;
  "seeds/diplomatic_network": typeof seeds_diplomatic_network;
  "seeds/diplomatic_network_dev": typeof seeds_diplomatic_network_dev;
  "seeds/diplomatic_network_espagne": typeof seeds_diplomatic_network_espagne;
  "seeds/guides_world": typeof seeds_guides_world;
  "seeds/listDevAccounts": typeof seeds_listDevAccounts;
  "seeds/listOrgStaff": typeof seeds_listOrgStaff;
  "seeds/roles": typeof seeds_roles;
  "seeds/seedDevAuthUsers": typeof seeds_seedDevAuthUsers;
  "seeds/seedDevCitizenProfiles": typeof seeds_seedDevCitizenProfiles;
  "seeds/seedFromJson": typeof seeds_seedFromJson;
  "seeds/seedOrgDetails": typeof seeds_seedOrgDetails;
  "seeds/seedOrgPublicDocs": typeof seeds_seedOrgPublicDocs;
  "seeds/seedPosts": typeof seeds_seedPosts;
  "seeds/seedShowcaseArticle": typeof seeds_seedShowcaseArticle;
  "seeds/seedUsers": typeof seeds_seedUsers;
  "seeds/serviceFormSchemas": typeof seeds_serviceFormSchemas;
  "seeds/staffAccounts": typeof seeds_staffAccounts;
  "seeds/tutorials": typeof seeds_tutorials;
  sensoriel: typeof sensoriel;
  testDumpRecords: typeof testDumpRecords;
  testQuery: typeof testQuery;
  testUser: typeof testUser;
  "triggers/index": typeof triggers_index;
  "triggers/skillsAggregation": typeof triggers_skillsAggregation;
  visuel: typeof visuel;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  betterAuth: import("@convex-dev/better-auth/_generated/component.js").ComponentApi<"betterAuth">;
  rateLimiter: import("@convex-dev/rate-limiter/_generated/component.js").ComponentApi<"rateLimiter">;
  resend: import("@convex-dev/resend/_generated/component.js").ComponentApi<"resend">;
  requestsByOrg: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"requestsByOrg">;
  membershipsByOrg: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"membershipsByOrg">;
  orgServicesByOrg: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"orgServicesByOrg">;
  globalCounts: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"globalCounts">;
  registrationsByOrg: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"registrationsByOrg">;
  requestsGlobal: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"requestsGlobal">;
  associationsGlobal: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"associationsGlobal">;
  companiesGlobal: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"companiesGlobal">;
  orgsGlobal: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"orgsGlobal">;
  servicesGlobal: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"servicesGlobal">;
  appointmentsByOrg: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"appointmentsByOrg">;
  childProfilesGlobal: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"childProfilesGlobal">;
  diplomaticTargetsByOrg: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"diplomaticTargetsByOrg">;
  diplomaticLettersByOrg: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"diplomaticLettersByOrg">;
  diplomaticPlansByOrg: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"diplomaticPlansByOrg">;
  diplomaticReportsByOrg: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"diplomaticReportsByOrg">;
  diplomaticProjectsByOrg: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"diplomaticProjectsByOrg">;
  correspondanceItemsByOrg: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"correspondanceItemsByOrg">;
  dossierProceduresByOrg: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"dossierProceduresByOrg">;
  documentsByOwnerCategory: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"documentsByOwnerCategory">;
  documentsByOwnerExpiry: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"documentsByOwnerExpiry">;
  missedCallsByOrgStatus: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"missedCallsByOrgStatus">;
  missedCallsByOrgReason: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"missedCallsByOrgReason">;
  requestsByOrgService: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"requestsByOrgService">;
  usersByRole: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"usersByRole">;
  usersByStatus: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"usersByStatus">;
  usersByCountry: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"usersByCountry">;
  membershipsByUser: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"membershipsByUser">;
  profilesByCategory: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"profilesByCategory">;
  profilesByProfessionStatus: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"profilesByProfessionStatus">;
  profilesByEnrichmentStatus: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"profilesByEnrichmentStatus">;
  cvSkillItemsByLevel: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"cvSkillItemsByLevel">;
};
