/**
 * Données mock TRAVAIL.GA — offres seedées d'employeurs gabonais plausibles.
 * Utilisé tant que les vraies données Convex (api.functions.pnpe.offresPubliques)
 * ne sont pas branchées sur les pages publiques. Source : design Claude `data.js`.
 */

import type { OffreCard } from "@/components/design/job-card";

export const MOCK_OFFRES: OffreCard[] = [
  {
    id: "ofr-1",
    ref: "OFR-2025-1842",
    titre: "Ingénieur Méthodes Maintenance — Site de Moanda",
    employeur: "COMILOG",
    employeurFull: "Compagnie Minière de l'Ogooué",
    verified: true,
    logo: { txt: "CO", bg: "#1B4D8C", fg: "#fff" },
    type: "ENTREPRISE",
    contrat: "CDI",
    ville: "Moanda",
    province: "HAUT_OGOOUE",
    salaireMin: 1_450_000,
    salaireMax: 1_850_000,
    devise: "XAF",
    poste: "il y a 2 jours",
    postePoint: 2,
    candidats: 47,
    teletravail: "Non",
    experience: "5+ ans",
    secteur: "Mines & Métallurgie",
    featured: true,
    description:
      "Au sein de la Direction Production de COMILOG, vous pilotez la fiabilisation des équipements stratégiques du complexe minier de Moanda (extraction et préparation du manganèse). Vous animez une équipe de 12 techniciens et coordonnez les arrêts planifiés avec les ateliers spécialisés.",
    missions: [
      "Définir et piloter le plan de maintenance préventive sur le périmètre extraction",
      "Animer les routines de fiabilité avec les chefs d'équipe (TPM, AMDEC)",
      "Coordonner les sous-traitants spécialisés lors des arrêts programmés",
      "Reporter au directeur production sur les indicateurs MTBF / MTTR",
    ],
    profil: [
      "Ingénieur généraliste, mécanique ou maintenance industrielle",
      "5+ ans en environnement minier, cimentier ou sidérurgique",
      "Maîtrise SAP-PM ou GMAO équivalente",
      "Mobilité Moanda — logement fourni",
    ],
    matching: 92,
  },
  {
    id: "ofr-2",
    ref: "OFR-2025-1839",
    titre: "Conducteur de train — Transgabonais",
    employeur: "SETRAG",
    employeurFull: "Société d'Exploitation du Transgabonais",
    verified: true,
    logo: { txt: "SE", bg: "#0F3F7A", fg: "#fff" },
    type: "ENTREPRISE",
    contrat: "CDI",
    ville: "Owendo",
    province: "ESTUAIRE",
    salaireMin: 780_000,
    salaireMax: 950_000,
    devise: "XAF",
    poste: "il y a 3 jours",
    postePoint: 3,
    candidats: 134,
    teletravail: "Non",
    experience: "Débutant accepté",
    secteur: "Transport & Logistique",
    description:
      "Rejoignez l'équipe de conduite du Transgabonais sur la ligne Owendo–Franceville. Formation initiale de 14 mois prise en charge intégralement (théorie + roulage accompagné).",
    matching: 71,
  },
  {
    id: "ofr-3",
    ref: "OFR-2025-1836",
    titre: "Chargé(e) de Projet ANPI — Formalisation TPE/PME",
    employeur: "ANPI-Gabon",
    employeurFull: "Agence Nationale de Promotion des Investissements",
    verified: true,
    logo: { txt: "AN", bg: "#16A37B", fg: "#fff" },
    type: "ADMINISTRATION",
    contrat: "CDD",
    ville: "Libreville",
    province: "ESTUAIRE",
    salaireMin: 850_000,
    salaireMax: 1_100_000,
    devise: "XAF",
    poste: "il y a 5 jours",
    postePoint: 5,
    candidats: 28,
    teletravail: "Hybride",
    experience: "3-5 ans",
    secteur: "Administration publique",
    description:
      "Au sein de la Direction de la Promotion, vous accompagnez les porteurs de projet Auto-Emploi PNPE jusqu'à la formalisation de leur entreprise via le guichet ANPI.",
    matching: 84,
  },
  {
    id: "ofr-4",
    ref: "OFR-2025-1833",
    titre: "Développeur Full-Stack TypeScript",
    employeur: "Gabon Telecom",
    employeurFull: "Gabon Telecom SA",
    verified: true,
    logo: { txt: "GT", bg: "#C8643D", fg: "#fff" },
    type: "ENTREPRISE",
    contrat: "CDI",
    ville: "Libreville",
    province: "ESTUAIRE",
    salaireMin: 1_100_000,
    salaireMax: 1_600_000,
    devise: "XAF",
    poste: "il y a 1 jour",
    postePoint: 1,
    candidats: 22,
    teletravail: "Hybride",
    experience: "3-5 ans",
    secteur: "Tech & Télécoms",
    urgent: true,
    description:
      "Au sein du pôle Digital Factory, vous concevez les services web grand public et BtoB de Gabon Telecom — facturation, espace client, mobile money.",
    matching: 95,
  },
  {
    id: "ofr-5",
    ref: "OFR-2025-1827",
    titre: "Agronome filière Palmier — Awala",
    employeur: "Olam Palm Gabon",
    employeurFull: "Olam Palm Gabon SA",
    verified: true,
    logo: { txt: "OP", bg: "#5A7E5F", fg: "#fff" },
    type: "ENTREPRISE",
    contrat: "CDD",
    ville: "Mouila",
    province: "NGOUNIE",
    salaireMin: 950_000,
    salaireMax: 1_250_000,
    devise: "XAF",
    poste: "il y a 6 jours",
    postePoint: 6,
    candidats: 19,
    teletravail: "Non",
    experience: "2-4 ans",
    secteur: "Agro-industrie",
    description:
      "Vous pilotez la conduite agronomique d'un bloc de 800 ha à Awala. Rotation 6/2.",
    matching: 67,
    vu: true,
  },
  {
    id: "ofr-6",
    ref: "OFR-2025-1825",
    titre: "Chargé(e) de Clientèle — Agence Charbonnages",
    employeur: "BGFI Bank Gabon",
    employeurFull: "BGFI Bank Gabon",
    verified: true,
    logo: { txt: "BG", bg: "#163E70", fg: "#fff" },
    type: "ENTREPRISE",
    contrat: "CDI",
    ville: "Libreville",
    province: "ESTUAIRE",
    salaireMin: 680_000,
    salaireMax: 850_000,
    devise: "XAF",
    poste: "il y a 1 semaine",
    postePoint: 7,
    candidats: 89,
    teletravail: "Non",
    experience: "2-4 ans",
    secteur: "Banque & Assurance",
    description:
      "Conseiller portefeuille particuliers premium en agence Charbonnages.",
    matching: 78,
  },
  {
    id: "ofr-7",
    ref: "OFR-2025-1822",
    titre: "Garde d'enfants à domicile — Quartier Glass",
    employeur: "Famille Ondo-Mba",
    employeurFull: "Particulier — Famille Ondo-Mba",
    verified: false,
    logo: { txt: "OM", bg: "#9C8068", fg: "#fff" },
    type: "PARTICULIER",
    contrat: "CDD",
    ville: "Libreville",
    province: "ESTUAIRE",
    salaireMin: 180_000,
    salaireMax: 220_000,
    devise: "XAF",
    poste: "il y a 4 jours",
    postePoint: 4,
    candidats: 12,
    teletravail: "Non",
    experience: "Débutant accepté",
    secteur: "Services à la personne",
    description:
      "Garde de 2 enfants (4 et 7 ans), du lundi au vendredi 13h–19h, quartier Glass.",
    matching: 58,
  },
  {
    id: "ofr-8",
    ref: "OFR-2025-1819",
    titre: "Technicien Production HSE — Plateforme Anguille",
    employeur: "TotalEnergies EP Gabon",
    employeurFull: "TotalEnergies EP Gabon",
    verified: true,
    logo: { txt: "TE", bg: "#0F1419", fg: "#fff" },
    type: "ENTREPRISE",
    contrat: "CDI",
    ville: "Port-Gentil",
    province: "OGOOUE_MARITIME",
    salaireMin: 1_700_000,
    salaireMax: 2_200_000,
    devise: "XAF",
    poste: "il y a 2 semaines",
    postePoint: 14,
    candidats: 56,
    teletravail: "Non",
    experience: "5+ ans",
    secteur: "Pétrole & Énergie",
    featured: true,
    description:
      "Sur la plateforme offshore Anguille, vous garantissez la conformité HSE des opérations de production. Rotation 4/4.",
    matching: 88,
  },
  {
    id: "ofr-9",
    ref: "OFR-2025-1816",
    titre: "Animateur(trice) Jeunesse — Maison de quartier",
    employeur: "Mairie de Libreville",
    employeurFull: "Mairie de Libreville",
    verified: true,
    logo: { txt: "ML", bg: "#16A37B", fg: "#fff" },
    type: "ADMINISTRATION",
    contrat: "CDD",
    ville: "Libreville",
    province: "ESTUAIRE",
    salaireMin: 350_000,
    salaireMax: 420_000,
    devise: "XAF",
    poste: "il y a 3 jours",
    postePoint: 3,
    candidats: 41,
    teletravail: "Non",
    experience: "Débutant accepté",
    secteur: "Action sociale",
    description:
      "Coordination des activités jeunesse de la Maison de quartier Akébé.",
    matching: 64,
  },
  {
    id: "ofr-10",
    ref: "OFR-2025-1814",
    titre: "Géologue Junior — Bassin sédimentaire",
    employeur: "Perenco Oil & Gas",
    employeurFull: "Perenco Oil & Gas Gabon",
    verified: true,
    logo: { txt: "PE", bg: "#7A1F2B", fg: "#fff" },
    type: "ENTREPRISE",
    contrat: "CDI",
    ville: "Port-Gentil",
    province: "OGOOUE_MARITIME",
    salaireMin: 1_250_000,
    salaireMax: 1_500_000,
    devise: "XAF",
    poste: "il y a 8 jours",
    postePoint: 8,
    candidats: 31,
    teletravail: "Non",
    experience: "1-3 ans",
    secteur: "Pétrole & Énergie",
    description:
      "Au sein de l'équipe Exploration, vous interprétez les données sismiques du bassin côtier gabonais.",
    matching: 81,
  },
];
