/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as SignInSplatRouteImport } from './routes/sign-in/$'
import { Route as AppIdocumentRouteImport } from './routes/_app/idocument'
import { Route as AppIcorrespondanceRouteImport } from './routes/_app/icorrespondance'
import { Route as AppIboiteRouteImport } from './routes/_app/iboite'
import { Route as AppIagendaRouteImport } from './routes/_app/iagenda'
import { Route as AppAssociationsRouteImport } from './routes/_app/associations'
import { Route as AppUsersIndexRouteImport } from './routes/_app/users/index'
import { Route as AppTutorialsIndexRouteImport } from './routes/_app/tutorials/index'
import { Route as AppSupportIndexRouteImport } from './routes/_app/support/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppServicesIndexRouteImport } from './routes/_app/services/index'
import { Route as AppRequestsIndexRouteImport } from './routes/_app/requests/index'
import { Route as AppRepsIndexRouteImport } from './routes/_app/reps/index'
import { Route as AppProfilesIndexRouteImport } from './routes/_app/profiles/index'
import { Route as AppPostsIndexRouteImport } from './routes/_app/posts/index'
import { Route as AppMonitoringIndexRouteImport } from './routes/_app/monitoring/index'
import { Route as AppEventsIndexRouteImport } from './routes/_app/events/index'
import { Route as AppAuditLogsIndexRouteImport } from './routes/_app/audit-logs/index'
import { Route as AppAffairesConsulairesIndexRouteImport } from './routes/_app/affaires-consulaires/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppUsersUserIdRouteImport } from './routes/_app/users/$userId'
import { Route as AppTutorialsNewRouteImport } from './routes/_app/tutorials/new'
import { Route as AppSupportTicketIdRouteImport } from './routes/_app/support/$ticketId'
import { Route as AppServicesNewRouteImport } from './routes/_app/services/new'
import { Route as AppRequestsRequestIdRouteImport } from './routes/_app/requests/$requestId'
import { Route as AppRepsNewRouteImport } from './routes/_app/reps/new'
import { Route as AppRepsOrgIdRouteImport } from './routes/_app/reps/$orgId'
import { Route as AppProfilesProfileIdRouteImport } from './routes/_app/profiles/$profileId'
import { Route as AppPostsNewRouteImport } from './routes/_app/posts/new'
import { Route as AppEventsNewRouteImport } from './routes/_app/events/new'
import { Route as AppConfigServicesRouteImport } from './routes/_app/config/services'
import { Route as AppConfigRepresentationsRouteImport } from './routes/_app/config/representations'
import { Route as AppConfigPrintSettingsRouteImport } from './routes/_app/config/print-settings'
import { Route as AppConfigPositionsRouteImport } from './routes/_app/config/positions'
import { Route as AppConfigModulesRouteImport } from './routes/_app/config/modules'
import { Route as AppTutorialsTutorialIdEditRouteImport } from './routes/_app/tutorials/$tutorialId.edit'
import { Route as AppServicesServiceIdFormBuilderRouteImport } from './routes/_app/services/$serviceId_.form-builder'
import { Route as AppServicesServiceIdEditRouteImport } from './routes/_app/services/$serviceId_.edit'
import { Route as AppRepsOrgIdEditRouteImport } from './routes/_app/reps/$orgId_.edit'
import { Route as AppPostsPostIdEditRouteImport } from './routes/_app/posts/$postId.edit'
import { Route as AppEventsEventIdEditRouteImport } from './routes/_app/events/$eventId.edit'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIdocumentRoute = AppIdocumentRouteImport.update({
  id: '/idocument',
  path: '/idocument',
  getParentRoute: () => AppRoute,
} as any)
const AppIcorrespondanceRoute = AppIcorrespondanceRouteImport.update({
  id: '/icorrespondance',
  path: '/icorrespondance',
  getParentRoute: () => AppRoute,
} as any)
const AppIboiteRoute = AppIboiteRouteImport.update({
  id: '/iboite',
  path: '/iboite',
  getParentRoute: () => AppRoute,
} as any)
const AppIagendaRoute = AppIagendaRouteImport.update({
  id: '/iagenda',
  path: '/iagenda',
  getParentRoute: () => AppRoute,
} as any)
const AppAssociationsRoute = AppAssociationsRouteImport.update({
  id: '/associations',
  path: '/associations',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppRoute,
} as any)
const AppTutorialsIndexRoute = AppTutorialsIndexRouteImport.update({
  id: '/tutorials/',
  path: '/tutorials/',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportIndexRoute = AppSupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesIndexRoute = AppServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsIndexRoute = AppRequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => AppRoute,
} as any)
const AppRepsIndexRoute = AppRepsIndexRouteImport.update({
  id: '/reps/',
  path: '/reps/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilesIndexRoute = AppProfilesIndexRouteImport.update({
  id: '/profiles/',
  path: '/profiles/',
  getParentRoute: () => AppRoute,
} as any)
const AppPostsIndexRoute = AppPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AppRoute,
} as any)
const AppMonitoringIndexRoute = AppMonitoringIndexRouteImport.update({
  id: '/monitoring/',
  path: '/monitoring/',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditLogsIndexRoute = AppAuditLogsIndexRouteImport.update({
  id: '/audit-logs/',
  path: '/audit-logs/',
  getParentRoute: () => AppRoute,
} as any)
const AppAffairesConsulairesIndexRoute =
  AppAffairesConsulairesIndexRouteImport.update({
    id: '/affaires-consulaires/',
    path: '/affaires-consulaires/',
    getParentRoute: () => AppRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersUserIdRoute = AppUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AppRoute,
} as any)
const AppTutorialsNewRoute = AppTutorialsNewRouteImport.update({
  id: '/tutorials/new',
  path: '/tutorials/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportTicketIdRoute = AppSupportTicketIdRouteImport.update({
  id: '/support/$ticketId',
  path: '/support/$ticketId',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesNewRoute = AppServicesNewRouteImport.update({
  id: '/services/new',
  path: '/services/new',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsRequestIdRoute = AppRequestsRequestIdRouteImport.update({
  id: '/requests/$requestId',
  path: '/requests/$requestId',
  getParentRoute: () => AppRoute,
} as any)
const AppRepsNewRoute = AppRepsNewRouteImport.update({
  id: '/reps/new',
  path: '/reps/new',
  getParentRoute: () => AppRoute,
} as any)
const AppRepsOrgIdRoute = AppRepsOrgIdRouteImport.update({
  id: '/reps/$orgId',
  path: '/reps/$orgId',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilesProfileIdRoute = AppProfilesProfileIdRouteImport.update({
  id: '/profiles/$profileId',
  path: '/profiles/$profileId',
  getParentRoute: () => AppRoute,
} as any)
const AppPostsNewRoute = AppPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsNewRoute = AppEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigServicesRoute = AppConfigServicesRouteImport.update({
  id: '/config/services',
  path: '/config/services',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigRepresentationsRoute =
  AppConfigRepresentationsRouteImport.update({
    id: '/config/representations',
    path: '/config/representations',
    getParentRoute: () => AppRoute,
  } as any)
const AppConfigPrintSettingsRoute = AppConfigPrintSettingsRouteImport.update({
  id: '/config/print-settings',
  path: '/config/print-settings',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigPositionsRoute = AppConfigPositionsRouteImport.update({
  id: '/config/positions',
  path: '/config/positions',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigModulesRoute = AppConfigModulesRouteImport.update({
  id: '/config/modules',
  path: '/config/modules',
  getParentRoute: () => AppRoute,
} as any)
const AppTutorialsTutorialIdEditRoute =
  AppTutorialsTutorialIdEditRouteImport.update({
    id: '/tutorials/$tutorialId/edit',
    path: '/tutorials/$tutorialId/edit',
    getParentRoute: () => AppRoute,
  } as any)
const AppServicesServiceIdFormBuilderRoute =
  AppServicesServiceIdFormBuilderRouteImport.update({
    id: '/services/$serviceId_/form-builder',
    path: '/services/$serviceId/form-builder',
    getParentRoute: () => AppRoute,
  } as any)
const AppServicesServiceIdEditRoute =
  AppServicesServiceIdEditRouteImport.update({
    id: '/services/$serviceId_/edit',
    path: '/services/$serviceId/edit',
    getParentRoute: () => AppRoute,
  } as any)
const AppRepsOrgIdEditRoute = AppRepsOrgIdEditRouteImport.update({
  id: '/reps/$orgId_/edit',
  path: '/reps/$orgId/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppPostsPostIdEditRoute = AppPostsPostIdEditRouteImport.update({
  id: '/posts/$postId/edit',
  path: '/posts/$postId/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsEventIdEditRoute = AppEventsEventIdEditRouteImport.update({
  id: '/events/$eventId/edit',
  path: '/events/$eventId/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/associations': typeof AppAssociationsRoute
  '/iagenda': typeof AppIagendaRoute
  '/iboite': typeof AppIboiteRoute
  '/icorrespondance': typeof AppIcorrespondanceRoute
  '/idocument': typeof AppIdocumentRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/config/modules': typeof AppConfigModulesRoute
  '/config/positions': typeof AppConfigPositionsRoute
  '/config/print-settings': typeof AppConfigPrintSettingsRoute
  '/config/representations': typeof AppConfigRepresentationsRoute
  '/config/services': typeof AppConfigServicesRoute
  '/events/new': typeof AppEventsNewRoute
  '/posts/new': typeof AppPostsNewRoute
  '/profiles/$profileId': typeof AppProfilesProfileIdRoute
  '/reps/$orgId': typeof AppRepsOrgIdRoute
  '/reps/new': typeof AppRepsNewRoute
  '/requests/$requestId': typeof AppRequestsRequestIdRoute
  '/services/new': typeof AppServicesNewRoute
  '/support/$ticketId': typeof AppSupportTicketIdRoute
  '/tutorials/new': typeof AppTutorialsNewRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/affaires-consulaires/': typeof AppAffairesConsulairesIndexRoute
  '/audit-logs/': typeof AppAuditLogsIndexRoute
  '/events/': typeof AppEventsIndexRoute
  '/monitoring/': typeof AppMonitoringIndexRoute
  '/posts/': typeof AppPostsIndexRoute
  '/profiles/': typeof AppProfilesIndexRoute
  '/reps/': typeof AppRepsIndexRoute
  '/requests/': typeof AppRequestsIndexRoute
  '/services/': typeof AppServicesIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/support/': typeof AppSupportIndexRoute
  '/tutorials/': typeof AppTutorialsIndexRoute
  '/users/': typeof AppUsersIndexRoute
  '/events/$eventId/edit': typeof AppEventsEventIdEditRoute
  '/posts/$postId/edit': typeof AppPostsPostIdEditRoute
  '/reps/$orgId/edit': typeof AppRepsOrgIdEditRoute
  '/services/$serviceId/edit': typeof AppServicesServiceIdEditRoute
  '/services/$serviceId/form-builder': typeof AppServicesServiceIdFormBuilderRoute
  '/tutorials/$tutorialId/edit': typeof AppTutorialsTutorialIdEditRoute
}
export interface FileRoutesByTo {
  '/associations': typeof AppAssociationsRoute
  '/iagenda': typeof AppIagendaRoute
  '/iboite': typeof AppIboiteRoute
  '/icorrespondance': typeof AppIcorrespondanceRoute
  '/idocument': typeof AppIdocumentRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/': typeof AppIndexRoute
  '/config/modules': typeof AppConfigModulesRoute
  '/config/positions': typeof AppConfigPositionsRoute
  '/config/print-settings': typeof AppConfigPrintSettingsRoute
  '/config/representations': typeof AppConfigRepresentationsRoute
  '/config/services': typeof AppConfigServicesRoute
  '/events/new': typeof AppEventsNewRoute
  '/posts/new': typeof AppPostsNewRoute
  '/profiles/$profileId': typeof AppProfilesProfileIdRoute
  '/reps/$orgId': typeof AppRepsOrgIdRoute
  '/reps/new': typeof AppRepsNewRoute
  '/requests/$requestId': typeof AppRequestsRequestIdRoute
  '/services/new': typeof AppServicesNewRoute
  '/support/$ticketId': typeof AppSupportTicketIdRoute
  '/tutorials/new': typeof AppTutorialsNewRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/affaires-consulaires': typeof AppAffairesConsulairesIndexRoute
  '/audit-logs': typeof AppAuditLogsIndexRoute
  '/events': typeof AppEventsIndexRoute
  '/monitoring': typeof AppMonitoringIndexRoute
  '/posts': typeof AppPostsIndexRoute
  '/profiles': typeof AppProfilesIndexRoute
  '/reps': typeof AppRepsIndexRoute
  '/requests': typeof AppRequestsIndexRoute
  '/services': typeof AppServicesIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/support': typeof AppSupportIndexRoute
  '/tutorials': typeof AppTutorialsIndexRoute
  '/users': typeof AppUsersIndexRoute
  '/events/$eventId/edit': typeof AppEventsEventIdEditRoute
  '/posts/$postId/edit': typeof AppPostsPostIdEditRoute
  '/reps/$orgId/edit': typeof AppRepsOrgIdEditRoute
  '/services/$serviceId/edit': typeof AppServicesServiceIdEditRoute
  '/services/$serviceId/form-builder': typeof AppServicesServiceIdFormBuilderRoute
  '/tutorials/$tutorialId/edit': typeof AppTutorialsTutorialIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/associations': typeof AppAssociationsRoute
  '/_app/iagenda': typeof AppIagendaRoute
  '/_app/iboite': typeof AppIboiteRoute
  '/_app/icorrespondance': typeof AppIcorrespondanceRoute
  '/_app/idocument': typeof AppIdocumentRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/_app/': typeof AppIndexRoute
  '/_app/config/modules': typeof AppConfigModulesRoute
  '/_app/config/positions': typeof AppConfigPositionsRoute
  '/_app/config/print-settings': typeof AppConfigPrintSettingsRoute
  '/_app/config/representations': typeof AppConfigRepresentationsRoute
  '/_app/config/services': typeof AppConfigServicesRoute
  '/_app/events/new': typeof AppEventsNewRoute
  '/_app/posts/new': typeof AppPostsNewRoute
  '/_app/profiles/$profileId': typeof AppProfilesProfileIdRoute
  '/_app/reps/$orgId': typeof AppRepsOrgIdRoute
  '/_app/reps/new': typeof AppRepsNewRoute
  '/_app/requests/$requestId': typeof AppRequestsRequestIdRoute
  '/_app/services/new': typeof AppServicesNewRoute
  '/_app/support/$ticketId': typeof AppSupportTicketIdRoute
  '/_app/tutorials/new': typeof AppTutorialsNewRoute
  '/_app/users/$userId': typeof AppUsersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/affaires-consulaires/': typeof AppAffairesConsulairesIndexRoute
  '/_app/audit-logs/': typeof AppAuditLogsIndexRoute
  '/_app/events/': typeof AppEventsIndexRoute
  '/_app/monitoring/': typeof AppMonitoringIndexRoute
  '/_app/posts/': typeof AppPostsIndexRoute
  '/_app/profiles/': typeof AppProfilesIndexRoute
  '/_app/reps/': typeof AppRepsIndexRoute
  '/_app/requests/': typeof AppRequestsIndexRoute
  '/_app/services/': typeof AppServicesIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/support/': typeof AppSupportIndexRoute
  '/_app/tutorials/': typeof AppTutorialsIndexRoute
  '/_app/users/': typeof AppUsersIndexRoute
  '/_app/events/$eventId/edit': typeof AppEventsEventIdEditRoute
  '/_app/posts/$postId/edit': typeof AppPostsPostIdEditRoute
  '/_app/reps/$orgId_/edit': typeof AppRepsOrgIdEditRoute
  '/_app/services/$serviceId_/edit': typeof AppServicesServiceIdEditRoute
  '/_app/services/$serviceId_/form-builder': typeof AppServicesServiceIdFormBuilderRoute
  '/_app/tutorials/$tutorialId/edit': typeof AppTutorialsTutorialIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/associations'
    | '/iagenda'
    | '/iboite'
    | '/icorrespondance'
    | '/idocument'
    | '/sign-in/$'
    | '/config/modules'
    | '/config/positions'
    | '/config/print-settings'
    | '/config/representations'
    | '/config/services'
    | '/events/new'
    | '/posts/new'
    | '/profiles/$profileId'
    | '/reps/$orgId'
    | '/reps/new'
    | '/requests/$requestId'
    | '/services/new'
    | '/support/$ticketId'
    | '/tutorials/new'
    | '/users/$userId'
    | '/api/auth/$'
    | '/affaires-consulaires/'
    | '/audit-logs/'
    | '/events/'
    | '/monitoring/'
    | '/posts/'
    | '/profiles/'
    | '/reps/'
    | '/requests/'
    | '/services/'
    | '/settings/'
    | '/support/'
    | '/tutorials/'
    | '/users/'
    | '/events/$eventId/edit'
    | '/posts/$postId/edit'
    | '/reps/$orgId/edit'
    | '/services/$serviceId/edit'
    | '/services/$serviceId/form-builder'
    | '/tutorials/$tutorialId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/associations'
    | '/iagenda'
    | '/iboite'
    | '/icorrespondance'
    | '/idocument'
    | '/sign-in/$'
    | '/'
    | '/config/modules'
    | '/config/positions'
    | '/config/print-settings'
    | '/config/representations'
    | '/config/services'
    | '/events/new'
    | '/posts/new'
    | '/profiles/$profileId'
    | '/reps/$orgId'
    | '/reps/new'
    | '/requests/$requestId'
    | '/services/new'
    | '/support/$ticketId'
    | '/tutorials/new'
    | '/users/$userId'
    | '/api/auth/$'
    | '/affaires-consulaires'
    | '/audit-logs'
    | '/events'
    | '/monitoring'
    | '/posts'
    | '/profiles'
    | '/reps'
    | '/requests'
    | '/services'
    | '/settings'
    | '/support'
    | '/tutorials'
    | '/users'
    | '/events/$eventId/edit'
    | '/posts/$postId/edit'
    | '/reps/$orgId/edit'
    | '/services/$serviceId/edit'
    | '/services/$serviceId/form-builder'
    | '/tutorials/$tutorialId/edit'
  id:
    | '__root__'
    | '/_app'
    | '/_app/associations'
    | '/_app/iagenda'
    | '/_app/iboite'
    | '/_app/icorrespondance'
    | '/_app/idocument'
    | '/sign-in/$'
    | '/_app/'
    | '/_app/config/modules'
    | '/_app/config/positions'
    | '/_app/config/print-settings'
    | '/_app/config/representations'
    | '/_app/config/services'
    | '/_app/events/new'
    | '/_app/posts/new'
    | '/_app/profiles/$profileId'
    | '/_app/reps/$orgId'
    | '/_app/reps/new'
    | '/_app/requests/$requestId'
    | '/_app/services/new'
    | '/_app/support/$ticketId'
    | '/_app/tutorials/new'
    | '/_app/users/$userId'
    | '/api/auth/$'
    | '/_app/affaires-consulaires/'
    | '/_app/audit-logs/'
    | '/_app/events/'
    | '/_app/monitoring/'
    | '/_app/posts/'
    | '/_app/profiles/'
    | '/_app/reps/'
    | '/_app/requests/'
    | '/_app/services/'
    | '/_app/settings/'
    | '/_app/support/'
    | '/_app/tutorials/'
    | '/_app/users/'
    | '/_app/events/$eventId/edit'
    | '/_app/posts/$postId/edit'
    | '/_app/reps/$orgId_/edit'
    | '/_app/services/$serviceId_/edit'
    | '/_app/services/$serviceId_/form-builder'
    | '/_app/tutorials/$tutorialId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SignInSplatRoute: typeof SignInSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/idocument': {
      id: '/_app/idocument'
      path: '/idocument'
      fullPath: '/idocument'
      preLoaderRoute: typeof AppIdocumentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/icorrespondance': {
      id: '/_app/icorrespondance'
      path: '/icorrespondance'
      fullPath: '/icorrespondance'
      preLoaderRoute: typeof AppIcorrespondanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/iboite': {
      id: '/_app/iboite'
      path: '/iboite'
      fullPath: '/iboite'
      preLoaderRoute: typeof AppIboiteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/iagenda': {
      id: '/_app/iagenda'
      path: '/iagenda'
      fullPath: '/iagenda'
      preLoaderRoute: typeof AppIagendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/associations': {
      id: '/_app/associations'
      path: '/associations'
      fullPath: '/associations'
      preLoaderRoute: typeof AppAssociationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/': {
      id: '/_app/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tutorials/': {
      id: '/_app/tutorials/'
      path: '/tutorials'
      fullPath: '/tutorials/'
      preLoaderRoute: typeof AppTutorialsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support/': {
      id: '/_app/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof AppSupportIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services/': {
      id: '/_app/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof AppServicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/requests/': {
      id: '/_app/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof AppRequestsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reps/': {
      id: '/_app/reps/'
      path: '/reps'
      fullPath: '/reps/'
      preLoaderRoute: typeof AppRepsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profiles/': {
      id: '/_app/profiles/'
      path: '/profiles'
      fullPath: '/profiles/'
      preLoaderRoute: typeof AppProfilesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/posts/': {
      id: '/_app/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof AppPostsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monitoring/': {
      id: '/_app/monitoring/'
      path: '/monitoring'
      fullPath: '/monitoring/'
      preLoaderRoute: typeof AppMonitoringIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/': {
      id: '/_app/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit-logs/': {
      id: '/_app/audit-logs/'
      path: '/audit-logs'
      fullPath: '/audit-logs/'
      preLoaderRoute: typeof AppAuditLogsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/affaires-consulaires/': {
      id: '/_app/affaires-consulaires/'
      path: '/affaires-consulaires'
      fullPath: '/affaires-consulaires/'
      preLoaderRoute: typeof AppAffairesConsulairesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users/$userId': {
      id: '/_app/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AppUsersUserIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tutorials/new': {
      id: '/_app/tutorials/new'
      path: '/tutorials/new'
      fullPath: '/tutorials/new'
      preLoaderRoute: typeof AppTutorialsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support/$ticketId': {
      id: '/_app/support/$ticketId'
      path: '/support/$ticketId'
      fullPath: '/support/$ticketId'
      preLoaderRoute: typeof AppSupportTicketIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services/new': {
      id: '/_app/services/new'
      path: '/services/new'
      fullPath: '/services/new'
      preLoaderRoute: typeof AppServicesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/requests/$requestId': {
      id: '/_app/requests/$requestId'
      path: '/requests/$requestId'
      fullPath: '/requests/$requestId'
      preLoaderRoute: typeof AppRequestsRequestIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reps/new': {
      id: '/_app/reps/new'
      path: '/reps/new'
      fullPath: '/reps/new'
      preLoaderRoute: typeof AppRepsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reps/$orgId': {
      id: '/_app/reps/$orgId'
      path: '/reps/$orgId'
      fullPath: '/reps/$orgId'
      preLoaderRoute: typeof AppRepsOrgIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profiles/$profileId': {
      id: '/_app/profiles/$profileId'
      path: '/profiles/$profileId'
      fullPath: '/profiles/$profileId'
      preLoaderRoute: typeof AppProfilesProfileIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/posts/new': {
      id: '/_app/posts/new'
      path: '/posts/new'
      fullPath: '/posts/new'
      preLoaderRoute: typeof AppPostsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/new': {
      id: '/_app/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof AppEventsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config/services': {
      id: '/_app/config/services'
      path: '/config/services'
      fullPath: '/config/services'
      preLoaderRoute: typeof AppConfigServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config/representations': {
      id: '/_app/config/representations'
      path: '/config/representations'
      fullPath: '/config/representations'
      preLoaderRoute: typeof AppConfigRepresentationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config/print-settings': {
      id: '/_app/config/print-settings'
      path: '/config/print-settings'
      fullPath: '/config/print-settings'
      preLoaderRoute: typeof AppConfigPrintSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config/positions': {
      id: '/_app/config/positions'
      path: '/config/positions'
      fullPath: '/config/positions'
      preLoaderRoute: typeof AppConfigPositionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config/modules': {
      id: '/_app/config/modules'
      path: '/config/modules'
      fullPath: '/config/modules'
      preLoaderRoute: typeof AppConfigModulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tutorials/$tutorialId/edit': {
      id: '/_app/tutorials/$tutorialId/edit'
      path: '/tutorials/$tutorialId/edit'
      fullPath: '/tutorials/$tutorialId/edit'
      preLoaderRoute: typeof AppTutorialsTutorialIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services/$serviceId_/form-builder': {
      id: '/_app/services/$serviceId_/form-builder'
      path: '/services/$serviceId/form-builder'
      fullPath: '/services/$serviceId/form-builder'
      preLoaderRoute: typeof AppServicesServiceIdFormBuilderRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services/$serviceId_/edit': {
      id: '/_app/services/$serviceId_/edit'
      path: '/services/$serviceId/edit'
      fullPath: '/services/$serviceId/edit'
      preLoaderRoute: typeof AppServicesServiceIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reps/$orgId_/edit': {
      id: '/_app/reps/$orgId_/edit'
      path: '/reps/$orgId/edit'
      fullPath: '/reps/$orgId/edit'
      preLoaderRoute: typeof AppRepsOrgIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/posts/$postId/edit': {
      id: '/_app/posts/$postId/edit'
      path: '/posts/$postId/edit'
      fullPath: '/posts/$postId/edit'
      preLoaderRoute: typeof AppPostsPostIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/$eventId/edit': {
      id: '/_app/events/$eventId/edit'
      path: '/events/$eventId/edit'
      fullPath: '/events/$eventId/edit'
      preLoaderRoute: typeof AppEventsEventIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAssociationsRoute: typeof AppAssociationsRoute
  AppIagendaRoute: typeof AppIagendaRoute
  AppIboiteRoute: typeof AppIboiteRoute
  AppIcorrespondanceRoute: typeof AppIcorrespondanceRoute
  AppIdocumentRoute: typeof AppIdocumentRoute
  AppIndexRoute: typeof AppIndexRoute
  AppConfigModulesRoute: typeof AppConfigModulesRoute
  AppConfigPositionsRoute: typeof AppConfigPositionsRoute
  AppConfigPrintSettingsRoute: typeof AppConfigPrintSettingsRoute
  AppConfigRepresentationsRoute: typeof AppConfigRepresentationsRoute
  AppConfigServicesRoute: typeof AppConfigServicesRoute
  AppEventsNewRoute: typeof AppEventsNewRoute
  AppPostsNewRoute: typeof AppPostsNewRoute
  AppProfilesProfileIdRoute: typeof AppProfilesProfileIdRoute
  AppRepsOrgIdRoute: typeof AppRepsOrgIdRoute
  AppRepsNewRoute: typeof AppRepsNewRoute
  AppRequestsRequestIdRoute: typeof AppRequestsRequestIdRoute
  AppServicesNewRoute: typeof AppServicesNewRoute
  AppSupportTicketIdRoute: typeof AppSupportTicketIdRoute
  AppTutorialsNewRoute: typeof AppTutorialsNewRoute
  AppUsersUserIdRoute: typeof AppUsersUserIdRoute
  AppAffairesConsulairesIndexRoute: typeof AppAffairesConsulairesIndexRoute
  AppAuditLogsIndexRoute: typeof AppAuditLogsIndexRoute
  AppEventsIndexRoute: typeof AppEventsIndexRoute
  AppMonitoringIndexRoute: typeof AppMonitoringIndexRoute
  AppPostsIndexRoute: typeof AppPostsIndexRoute
  AppProfilesIndexRoute: typeof AppProfilesIndexRoute
  AppRepsIndexRoute: typeof AppRepsIndexRoute
  AppRequestsIndexRoute: typeof AppRequestsIndexRoute
  AppServicesIndexRoute: typeof AppServicesIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppSupportIndexRoute: typeof AppSupportIndexRoute
  AppTutorialsIndexRoute: typeof AppTutorialsIndexRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
  AppEventsEventIdEditRoute: typeof AppEventsEventIdEditRoute
  AppPostsPostIdEditRoute: typeof AppPostsPostIdEditRoute
  AppRepsOrgIdEditRoute: typeof AppRepsOrgIdEditRoute
  AppServicesServiceIdEditRoute: typeof AppServicesServiceIdEditRoute
  AppServicesServiceIdFormBuilderRoute: typeof AppServicesServiceIdFormBuilderRoute
  AppTutorialsTutorialIdEditRoute: typeof AppTutorialsTutorialIdEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssociationsRoute: AppAssociationsRoute,
  AppIagendaRoute: AppIagendaRoute,
  AppIboiteRoute: AppIboiteRoute,
  AppIcorrespondanceRoute: AppIcorrespondanceRoute,
  AppIdocumentRoute: AppIdocumentRoute,
  AppIndexRoute: AppIndexRoute,
  AppConfigModulesRoute: AppConfigModulesRoute,
  AppConfigPositionsRoute: AppConfigPositionsRoute,
  AppConfigPrintSettingsRoute: AppConfigPrintSettingsRoute,
  AppConfigRepresentationsRoute: AppConfigRepresentationsRoute,
  AppConfigServicesRoute: AppConfigServicesRoute,
  AppEventsNewRoute: AppEventsNewRoute,
  AppPostsNewRoute: AppPostsNewRoute,
  AppProfilesProfileIdRoute: AppProfilesProfileIdRoute,
  AppRepsOrgIdRoute: AppRepsOrgIdRoute,
  AppRepsNewRoute: AppRepsNewRoute,
  AppRequestsRequestIdRoute: AppRequestsRequestIdRoute,
  AppServicesNewRoute: AppServicesNewRoute,
  AppSupportTicketIdRoute: AppSupportTicketIdRoute,
  AppTutorialsNewRoute: AppTutorialsNewRoute,
  AppUsersUserIdRoute: AppUsersUserIdRoute,
  AppAffairesConsulairesIndexRoute: AppAffairesConsulairesIndexRoute,
  AppAuditLogsIndexRoute: AppAuditLogsIndexRoute,
  AppEventsIndexRoute: AppEventsIndexRoute,
  AppMonitoringIndexRoute: AppMonitoringIndexRoute,
  AppPostsIndexRoute: AppPostsIndexRoute,
  AppProfilesIndexRoute: AppProfilesIndexRoute,
  AppRepsIndexRoute: AppRepsIndexRoute,
  AppRequestsIndexRoute: AppRequestsIndexRoute,
  AppServicesIndexRoute: AppServicesIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppSupportIndexRoute: AppSupportIndexRoute,
  AppTutorialsIndexRoute: AppTutorialsIndexRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
  AppEventsEventIdEditRoute: AppEventsEventIdEditRoute,
  AppPostsPostIdEditRoute: AppPostsPostIdEditRoute,
  AppRepsOrgIdEditRoute: AppRepsOrgIdEditRoute,
  AppServicesServiceIdEditRoute: AppServicesServiceIdEditRoute,
  AppServicesServiceIdFormBuilderRoute: AppServicesServiceIdFormBuilderRoute,
  AppTutorialsTutorialIdEditRoute: AppTutorialsTutorialIdEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SignInSplatRoute: SignInSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
