/**
 * Mapping ISO code pays → zone géographique pour le regroupement
 * des représentations diplomatiques.
 *
 * Source : géographie standard ONU + adaptations diplomatiques (ex: Égypte
 * en Afrique malgré son rôle culturel au Moyen-Orient).
 */

export const CONTINENT_MAP: Record<string, string> = {
	// Afrique
	CM: "Afrique",
	CG: "Afrique",
	CD: "Afrique",
	GQ: "Afrique",
	TD: "Afrique",
	CF: "Afrique",
	GA: "Afrique",
	ST: "Afrique",
	SN: "Afrique",
	CI: "Afrique",
	GH: "Afrique",
	NG: "Afrique",
	BJ: "Afrique",
	TG: "Afrique",
	BF: "Afrique",
	ML: "Afrique",
	GN: "Afrique",
	NE: "Afrique",
	GM: "Afrique",
	GW: "Afrique",
	SL: "Afrique",
	LR: "Afrique",
	CV: "Afrique",
	MR: "Afrique",
	KE: "Afrique",
	ET: "Afrique",
	TZ: "Afrique",
	UG: "Afrique",
	RW: "Afrique",
	BI: "Afrique",
	DJ: "Afrique",
	ER: "Afrique",
	SO: "Afrique",
	SD: "Afrique",
	SS: "Afrique",
	MG: "Afrique",
	MU: "Afrique",
	SC: "Afrique",
	KM: "Afrique",
	ZA: "Afrique",
	AO: "Afrique",
	MZ: "Afrique",
	ZM: "Afrique",
	ZW: "Afrique",
	BW: "Afrique",
	NA: "Afrique",
	MW: "Afrique",
	LS: "Afrique",
	SZ: "Afrique",
	MA: "Afrique",
	DZ: "Afrique",
	TN: "Afrique",
	LY: "Afrique",
	EG: "Afrique",
	// Europe
	FR: "Europe",
	DE: "Europe",
	GB: "Europe",
	ES: "Europe",
	IT: "Europe",
	BE: "Europe",
	CH: "Europe",
	PT: "Europe",
	NL: "Europe",
	AT: "Europe",
	SE: "Europe",
	NO: "Europe",
	DK: "Europe",
	FI: "Europe",
	IE: "Europe",
	PL: "Europe",
	CZ: "Europe",
	RO: "Europe",
	HU: "Europe",
	GR: "Europe",
	BG: "Europe",
	HR: "Europe",
	SK: "Europe",
	SI: "Europe",
	LT: "Europe",
	LV: "Europe",
	EE: "Europe",
	LU: "Europe",
	MT: "Europe",
	CY: "Europe",
	IS: "Europe",
	MC: "Europe",
	AD: "Europe",
	RS: "Europe",
	BA: "Europe",
	ME: "Europe",
	MK: "Europe",
	AL: "Europe",
	MD: "Europe",
	UA: "Europe",
	BY: "Europe",
	RU: "Europe",
	VA: "Europe",
	// Amérique du Nord
	US: "Amérique du Nord",
	CA: "Amérique du Nord",
	MX: "Amérique du Nord",
	// Amérique Latine & Caraïbes
	BR: "Amérique Latine",
	AR: "Amérique Latine",
	CL: "Amérique Latine",
	CO: "Amérique Latine",
	PE: "Amérique Latine",
	VE: "Amérique Latine",
	EC: "Amérique Latine",
	BO: "Amérique Latine",
	PY: "Amérique Latine",
	UY: "Amérique Latine",
	CR: "Amérique Latine",
	PA: "Amérique Latine",
	CU: "Amérique Latine",
	DO: "Amérique Latine",
	GT: "Amérique Latine",
	HN: "Amérique Latine",
	SV: "Amérique Latine",
	NI: "Amérique Latine",
	HT: "Amérique Latine",
	JM: "Amérique Latine",
	TT: "Amérique Latine",
	// Asie
	CN: "Asie",
	JP: "Asie",
	KR: "Asie",
	IN: "Asie",
	ID: "Asie",
	TH: "Asie",
	VN: "Asie",
	MY: "Asie",
	SG: "Asie",
	PH: "Asie",
	MM: "Asie",
	KH: "Asie",
	LA: "Asie",
	BD: "Asie",
	LK: "Asie",
	NP: "Asie",
	PK: "Asie",
	AF: "Asie",
	KZ: "Asie",
	UZ: "Asie",
	TM: "Asie",
	KG: "Asie",
	TJ: "Asie",
	MN: "Asie",
	TW: "Asie",
	KP: "Asie",
	// Moyen-Orient
	SA: "Moyen-Orient",
	AE: "Moyen-Orient",
	QA: "Moyen-Orient",
	KW: "Moyen-Orient",
	BH: "Moyen-Orient",
	OM: "Moyen-Orient",
	IL: "Moyen-Orient",
	JO: "Moyen-Orient",
	LB: "Moyen-Orient",
	IQ: "Moyen-Orient",
	IR: "Moyen-Orient",
	SY: "Moyen-Orient",
	YE: "Moyen-Orient",
	TR: "Moyen-Orient",
	PS: "Moyen-Orient",
	// Océanie
	AU: "Océanie",
	NZ: "Océanie",
	FJ: "Océanie",
	PG: "Océanie",
};

export const ZONE_ORDER = [
	"Afrique",
	"Europe",
	"Amérique du Nord",
	"Amérique Latine",
	"Asie",
	"Moyen-Orient",
	"Océanie",
	"Autres",
];

export function getContinent(countryCode: string): string {
	return CONTINENT_MAP[countryCode?.toUpperCase()] ?? "Autres";
}
