/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppStatisticsRouteImport } from './routes/_app/statistics'
import { Route as AppPaymentsRouteImport } from './routes/_app/payments'
import { Route as AppIdocumentRouteImport } from './routes/_app/idocument'
import { Route as AppIcorrespondanceRouteImport } from './routes/_app/icorrespondance'
import { Route as AppIboiteRouteImport } from './routes/_app/iboite'
import { Route as AppIastedRouteImport } from './routes/_app/iasted'
import { Route as AppIarchiveRouteImport } from './routes/_app/iarchive'
import { Route as AppIagendaRouteImport } from './routes/_app/iagenda'
import { Route as AppCallsRouteImport } from './routes/_app/calls'
import { Route as AppAffairesDiplomatiquesRouteImport } from './routes/_app/affaires-diplomatiques'
import { Route as AppAffairesConsulairesRouteImport } from './routes/_app/affaires-consulaires'
import { Route as AppTeamIndexRouteImport } from './routes/_app/team/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppServicesIndexRouteImport } from './routes/_app/services/index'
import { Route as AppRequestsIndexRouteImport } from './routes/_app/requests/index'
import { Route as AppPostsIndexRouteImport } from './routes/_app/posts/index'
import { Route as AppMeetingsIndexRouteImport } from './routes/_app/meetings/index'
import { Route as AppConsularRegistryIndexRouteImport } from './routes/_app/consular-registry/index'
import { Route as AppAppointmentsIndexRouteImport } from './routes/_app/appointments/index'
import { Route as ApiDevSignInRouteImport } from './routes/api/dev/sign-in'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppRequestsReferenceRouteImport } from './routes/_app/requests/$reference'
import { Route as AppProfilesProfileIdRouteImport } from './routes/_app/profiles/$profileId'
import { Route as AppPostsNewRouteImport } from './routes/_app/posts/new'
import { Route as AppConsularRegistryPrintQueueRouteImport } from './routes/_app/consular-registry/print-queue'
import { Route as AppAppointmentsAgentSchedulesRouteImport } from './routes/_app/appointments/agent-schedules'
import { Route as AppAppointmentsAppointmentIdRouteImport } from './routes/_app/appointments/$appointmentId'
import { Route as AppAffairesConsulairesProfilesIndexRouteImport } from './routes/_app/affaires-consulaires/profiles/index'
import { Route as AppServicesServiceIdEditRouteImport } from './routes/_app/services/$serviceId.edit'
import { Route as AppPostsPostIdEditRouteImport } from './routes/_app/posts/$postId.edit'
import { Route as AppAffairesConsulairesProfilesProfileIdRouteImport } from './routes/_app/affaires-consulaires/profiles/$profileId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppStatisticsRoute = AppStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppIdocumentRoute = AppIdocumentRouteImport.update({
  id: '/idocument',
  path: '/idocument',
  getParentRoute: () => AppRoute,
} as any)
const AppIcorrespondanceRoute = AppIcorrespondanceRouteImport.update({
  id: '/icorrespondance',
  path: '/icorrespondance',
  getParentRoute: () => AppRoute,
} as any)
const AppIboiteRoute = AppIboiteRouteImport.update({
  id: '/iboite',
  path: '/iboite',
  getParentRoute: () => AppRoute,
} as any)
const AppIastedRoute = AppIastedRouteImport.update({
  id: '/iasted',
  path: '/iasted',
  getParentRoute: () => AppRoute,
} as any)
const AppIarchiveRoute = AppIarchiveRouteImport.update({
  id: '/iarchive',
  path: '/iarchive',
  getParentRoute: () => AppRoute,
} as any)
const AppIagendaRoute = AppIagendaRouteImport.update({
  id: '/iagenda',
  path: '/iagenda',
  getParentRoute: () => AppRoute,
} as any)
const AppCallsRoute = AppCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AppRoute,
} as any)
const AppAffairesDiplomatiquesRoute =
  AppAffairesDiplomatiquesRouteImport.update({
    id: '/affaires-diplomatiques',
    path: '/affaires-diplomatiques',
    getParentRoute: () => AppRoute,
  } as any)
const AppAffairesConsulairesRoute = AppAffairesConsulairesRouteImport.update({
  id: '/affaires-consulaires',
  path: '/affaires-consulaires',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamIndexRoute = AppTeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesIndexRoute = AppServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsIndexRoute = AppRequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => AppRoute,
} as any)
const AppPostsIndexRoute = AppPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingsIndexRoute = AppMeetingsIndexRouteImport.update({
  id: '/meetings/',
  path: '/meetings/',
  getParentRoute: () => AppRoute,
} as any)
const AppConsularRegistryIndexRoute =
  AppConsularRegistryIndexRouteImport.update({
    id: '/consular-registry/',
    path: '/consular-registry/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAppointmentsIndexRoute = AppAppointmentsIndexRouteImport.update({
  id: '/appointments/',
  path: '/appointments/',
  getParentRoute: () => AppRoute,
} as any)
const ApiDevSignInRoute = ApiDevSignInRouteImport.update({
  id: '/api/dev/sign-in',
  path: '/api/dev/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRequestsReferenceRoute = AppRequestsReferenceRouteImport.update({
  id: '/requests/$reference',
  path: '/requests/$reference',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilesProfileIdRoute = AppProfilesProfileIdRouteImport.update({
  id: '/profiles/$profileId',
  path: '/profiles/$profileId',
  getParentRoute: () => AppRoute,
} as any)
const AppPostsNewRoute = AppPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => AppRoute,
} as any)
const AppConsularRegistryPrintQueueRoute =
  AppConsularRegistryPrintQueueRouteImport.update({
    id: '/consular-registry/print-queue',
    path: '/consular-registry/print-queue',
    getParentRoute: () => AppRoute,
  } as any)
const AppAppointmentsAgentSchedulesRoute =
  AppAppointmentsAgentSchedulesRouteImport.update({
    id: '/appointments/agent-schedules',
    path: '/appointments/agent-schedules',
    getParentRoute: () => AppRoute,
  } as any)
const AppAppointmentsAppointmentIdRoute =
  AppAppointmentsAppointmentIdRouteImport.update({
    id: '/appointments/$appointmentId',
    path: '/appointments/$appointmentId',
    getParentRoute: () => AppRoute,
  } as any)
const AppAffairesConsulairesProfilesIndexRoute =
  AppAffairesConsulairesProfilesIndexRouteImport.update({
    id: '/profiles/',
    path: '/profiles/',
    getParentRoute: () => AppAffairesConsulairesRoute,
  } as any)
const AppServicesServiceIdEditRoute =
  AppServicesServiceIdEditRouteImport.update({
    id: '/services/$serviceId/edit',
    path: '/services/$serviceId/edit',
    getParentRoute: () => AppRoute,
  } as any)
const AppPostsPostIdEditRoute = AppPostsPostIdEditRouteImport.update({
  id: '/posts/$postId/edit',
  path: '/posts/$postId/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppAffairesConsulairesProfilesProfileIdRoute =
  AppAffairesConsulairesProfilesProfileIdRouteImport.update({
    id: '/profiles/$profileId',
    path: '/profiles/$profileId',
    getParentRoute: () => AppAffairesConsulairesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/affaires-consulaires': typeof AppAffairesConsulairesRouteWithChildren
  '/affaires-diplomatiques': typeof AppAffairesDiplomatiquesRoute
  '/calls': typeof AppCallsRoute
  '/iagenda': typeof AppIagendaRoute
  '/iarchive': typeof AppIarchiveRoute
  '/iasted': typeof AppIastedRoute
  '/iboite': typeof AppIboiteRoute
  '/icorrespondance': typeof AppIcorrespondanceRoute
  '/idocument': typeof AppIdocumentRoute
  '/payments': typeof AppPaymentsRoute
  '/statistics': typeof AppStatisticsRoute
  '/appointments/$appointmentId': typeof AppAppointmentsAppointmentIdRoute
  '/appointments/agent-schedules': typeof AppAppointmentsAgentSchedulesRoute
  '/consular-registry/print-queue': typeof AppConsularRegistryPrintQueueRoute
  '/posts/new': typeof AppPostsNewRoute
  '/profiles/$profileId': typeof AppProfilesProfileIdRoute
  '/requests/$reference': typeof AppRequestsReferenceRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/dev/sign-in': typeof ApiDevSignInRoute
  '/appointments/': typeof AppAppointmentsIndexRoute
  '/consular-registry/': typeof AppConsularRegistryIndexRoute
  '/meetings/': typeof AppMeetingsIndexRoute
  '/posts/': typeof AppPostsIndexRoute
  '/requests/': typeof AppRequestsIndexRoute
  '/services/': typeof AppServicesIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/team/': typeof AppTeamIndexRoute
  '/affaires-consulaires/profiles/$profileId': typeof AppAffairesConsulairesProfilesProfileIdRoute
  '/posts/$postId/edit': typeof AppPostsPostIdEditRoute
  '/services/$serviceId/edit': typeof AppServicesServiceIdEditRoute
  '/affaires-consulaires/profiles/': typeof AppAffairesConsulairesProfilesIndexRoute
}
export interface FileRoutesByTo {
  '/affaires-consulaires': typeof AppAffairesConsulairesRouteWithChildren
  '/affaires-diplomatiques': typeof AppAffairesDiplomatiquesRoute
  '/calls': typeof AppCallsRoute
  '/iagenda': typeof AppIagendaRoute
  '/iarchive': typeof AppIarchiveRoute
  '/iasted': typeof AppIastedRoute
  '/iboite': typeof AppIboiteRoute
  '/icorrespondance': typeof AppIcorrespondanceRoute
  '/idocument': typeof AppIdocumentRoute
  '/payments': typeof AppPaymentsRoute
  '/statistics': typeof AppStatisticsRoute
  '/': typeof AppIndexRoute
  '/appointments/$appointmentId': typeof AppAppointmentsAppointmentIdRoute
  '/appointments/agent-schedules': typeof AppAppointmentsAgentSchedulesRoute
  '/consular-registry/print-queue': typeof AppConsularRegistryPrintQueueRoute
  '/posts/new': typeof AppPostsNewRoute
  '/profiles/$profileId': typeof AppProfilesProfileIdRoute
  '/requests/$reference': typeof AppRequestsReferenceRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/dev/sign-in': typeof ApiDevSignInRoute
  '/appointments': typeof AppAppointmentsIndexRoute
  '/consular-registry': typeof AppConsularRegistryIndexRoute
  '/meetings': typeof AppMeetingsIndexRoute
  '/posts': typeof AppPostsIndexRoute
  '/requests': typeof AppRequestsIndexRoute
  '/services': typeof AppServicesIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/team': typeof AppTeamIndexRoute
  '/affaires-consulaires/profiles/$profileId': typeof AppAffairesConsulairesProfilesProfileIdRoute
  '/posts/$postId/edit': typeof AppPostsPostIdEditRoute
  '/services/$serviceId/edit': typeof AppServicesServiceIdEditRoute
  '/affaires-consulaires/profiles': typeof AppAffairesConsulairesProfilesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/affaires-consulaires': typeof AppAffairesConsulairesRouteWithChildren
  '/_app/affaires-diplomatiques': typeof AppAffairesDiplomatiquesRoute
  '/_app/calls': typeof AppCallsRoute
  '/_app/iagenda': typeof AppIagendaRoute
  '/_app/iarchive': typeof AppIarchiveRoute
  '/_app/iasted': typeof AppIastedRoute
  '/_app/iboite': typeof AppIboiteRoute
  '/_app/icorrespondance': typeof AppIcorrespondanceRoute
  '/_app/idocument': typeof AppIdocumentRoute
  '/_app/payments': typeof AppPaymentsRoute
  '/_app/statistics': typeof AppStatisticsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/appointments/$appointmentId': typeof AppAppointmentsAppointmentIdRoute
  '/_app/appointments/agent-schedules': typeof AppAppointmentsAgentSchedulesRoute
  '/_app/consular-registry/print-queue': typeof AppConsularRegistryPrintQueueRoute
  '/_app/posts/new': typeof AppPostsNewRoute
  '/_app/profiles/$profileId': typeof AppProfilesProfileIdRoute
  '/_app/requests/$reference': typeof AppRequestsReferenceRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/dev/sign-in': typeof ApiDevSignInRoute
  '/_app/appointments/': typeof AppAppointmentsIndexRoute
  '/_app/consular-registry/': typeof AppConsularRegistryIndexRoute
  '/_app/meetings/': typeof AppMeetingsIndexRoute
  '/_app/posts/': typeof AppPostsIndexRoute
  '/_app/requests/': typeof AppRequestsIndexRoute
  '/_app/services/': typeof AppServicesIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/team/': typeof AppTeamIndexRoute
  '/_app/affaires-consulaires/profiles/$profileId': typeof AppAffairesConsulairesProfilesProfileIdRoute
  '/_app/posts/$postId/edit': typeof AppPostsPostIdEditRoute
  '/_app/services/$serviceId/edit': typeof AppServicesServiceIdEditRoute
  '/_app/affaires-consulaires/profiles/': typeof AppAffairesConsulairesProfilesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/affaires-consulaires'
    | '/affaires-diplomatiques'
    | '/calls'
    | '/iagenda'
    | '/iarchive'
    | '/iasted'
    | '/iboite'
    | '/icorrespondance'
    | '/idocument'
    | '/payments'
    | '/statistics'
    | '/appointments/$appointmentId'
    | '/appointments/agent-schedules'
    | '/consular-registry/print-queue'
    | '/posts/new'
    | '/profiles/$profileId'
    | '/requests/$reference'
    | '/api/auth/$'
    | '/api/dev/sign-in'
    | '/appointments/'
    | '/consular-registry/'
    | '/meetings/'
    | '/posts/'
    | '/requests/'
    | '/services/'
    | '/settings/'
    | '/team/'
    | '/affaires-consulaires/profiles/$profileId'
    | '/posts/$postId/edit'
    | '/services/$serviceId/edit'
    | '/affaires-consulaires/profiles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/affaires-consulaires'
    | '/affaires-diplomatiques'
    | '/calls'
    | '/iagenda'
    | '/iarchive'
    | '/iasted'
    | '/iboite'
    | '/icorrespondance'
    | '/idocument'
    | '/payments'
    | '/statistics'
    | '/'
    | '/appointments/$appointmentId'
    | '/appointments/agent-schedules'
    | '/consular-registry/print-queue'
    | '/posts/new'
    | '/profiles/$profileId'
    | '/requests/$reference'
    | '/api/auth/$'
    | '/api/dev/sign-in'
    | '/appointments'
    | '/consular-registry'
    | '/meetings'
    | '/posts'
    | '/requests'
    | '/services'
    | '/settings'
    | '/team'
    | '/affaires-consulaires/profiles/$profileId'
    | '/posts/$postId/edit'
    | '/services/$serviceId/edit'
    | '/affaires-consulaires/profiles'
  id:
    | '__root__'
    | '/_app'
    | '/_app/affaires-consulaires'
    | '/_app/affaires-diplomatiques'
    | '/_app/calls'
    | '/_app/iagenda'
    | '/_app/iarchive'
    | '/_app/iasted'
    | '/_app/iboite'
    | '/_app/icorrespondance'
    | '/_app/idocument'
    | '/_app/payments'
    | '/_app/statistics'
    | '/_app/'
    | '/_app/appointments/$appointmentId'
    | '/_app/appointments/agent-schedules'
    | '/_app/consular-registry/print-queue'
    | '/_app/posts/new'
    | '/_app/profiles/$profileId'
    | '/_app/requests/$reference'
    | '/api/auth/$'
    | '/api/dev/sign-in'
    | '/_app/appointments/'
    | '/_app/consular-registry/'
    | '/_app/meetings/'
    | '/_app/posts/'
    | '/_app/requests/'
    | '/_app/services/'
    | '/_app/settings/'
    | '/_app/team/'
    | '/_app/affaires-consulaires/profiles/$profileId'
    | '/_app/posts/$postId/edit'
    | '/_app/services/$serviceId/edit'
    | '/_app/affaires-consulaires/profiles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDevSignInRoute: typeof ApiDevSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/statistics': {
      id: '/_app/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof AppStatisticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments': {
      id: '/_app/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/idocument': {
      id: '/_app/idocument'
      path: '/idocument'
      fullPath: '/idocument'
      preLoaderRoute: typeof AppIdocumentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/icorrespondance': {
      id: '/_app/icorrespondance'
      path: '/icorrespondance'
      fullPath: '/icorrespondance'
      preLoaderRoute: typeof AppIcorrespondanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/iboite': {
      id: '/_app/iboite'
      path: '/iboite'
      fullPath: '/iboite'
      preLoaderRoute: typeof AppIboiteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/iasted': {
      id: '/_app/iasted'
      path: '/iasted'
      fullPath: '/iasted'
      preLoaderRoute: typeof AppIastedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/iarchive': {
      id: '/_app/iarchive'
      path: '/iarchive'
      fullPath: '/iarchive'
      preLoaderRoute: typeof AppIarchiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/iagenda': {
      id: '/_app/iagenda'
      path: '/iagenda'
      fullPath: '/iagenda'
      preLoaderRoute: typeof AppIagendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calls': {
      id: '/_app/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof AppCallsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/affaires-diplomatiques': {
      id: '/_app/affaires-diplomatiques'
      path: '/affaires-diplomatiques'
      fullPath: '/affaires-diplomatiques'
      preLoaderRoute: typeof AppAffairesDiplomatiquesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/affaires-consulaires': {
      id: '/_app/affaires-consulaires'
      path: '/affaires-consulaires'
      fullPath: '/affaires-consulaires'
      preLoaderRoute: typeof AppAffairesConsulairesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team/': {
      id: '/_app/team/'
      path: '/team'
      fullPath: '/team/'
      preLoaderRoute: typeof AppTeamIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services/': {
      id: '/_app/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof AppServicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/requests/': {
      id: '/_app/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof AppRequestsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/posts/': {
      id: '/_app/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof AppPostsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meetings/': {
      id: '/_app/meetings/'
      path: '/meetings'
      fullPath: '/meetings/'
      preLoaderRoute: typeof AppMeetingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consular-registry/': {
      id: '/_app/consular-registry/'
      path: '/consular-registry'
      fullPath: '/consular-registry/'
      preLoaderRoute: typeof AppConsularRegistryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/appointments/': {
      id: '/_app/appointments/'
      path: '/appointments'
      fullPath: '/appointments/'
      preLoaderRoute: typeof AppAppointmentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/dev/sign-in': {
      id: '/api/dev/sign-in'
      path: '/api/dev/sign-in'
      fullPath: '/api/dev/sign-in'
      preLoaderRoute: typeof ApiDevSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/requests/$reference': {
      id: '/_app/requests/$reference'
      path: '/requests/$reference'
      fullPath: '/requests/$reference'
      preLoaderRoute: typeof AppRequestsReferenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profiles/$profileId': {
      id: '/_app/profiles/$profileId'
      path: '/profiles/$profileId'
      fullPath: '/profiles/$profileId'
      preLoaderRoute: typeof AppProfilesProfileIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/posts/new': {
      id: '/_app/posts/new'
      path: '/posts/new'
      fullPath: '/posts/new'
      preLoaderRoute: typeof AppPostsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consular-registry/print-queue': {
      id: '/_app/consular-registry/print-queue'
      path: '/consular-registry/print-queue'
      fullPath: '/consular-registry/print-queue'
      preLoaderRoute: typeof AppConsularRegistryPrintQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/appointments/agent-schedules': {
      id: '/_app/appointments/agent-schedules'
      path: '/appointments/agent-schedules'
      fullPath: '/appointments/agent-schedules'
      preLoaderRoute: typeof AppAppointmentsAgentSchedulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/appointments/$appointmentId': {
      id: '/_app/appointments/$appointmentId'
      path: '/appointments/$appointmentId'
      fullPath: '/appointments/$appointmentId'
      preLoaderRoute: typeof AppAppointmentsAppointmentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/affaires-consulaires/profiles/': {
      id: '/_app/affaires-consulaires/profiles/'
      path: '/profiles'
      fullPath: '/affaires-consulaires/profiles/'
      preLoaderRoute: typeof AppAffairesConsulairesProfilesIndexRouteImport
      parentRoute: typeof AppAffairesConsulairesRoute
    }
    '/_app/services/$serviceId/edit': {
      id: '/_app/services/$serviceId/edit'
      path: '/services/$serviceId/edit'
      fullPath: '/services/$serviceId/edit'
      preLoaderRoute: typeof AppServicesServiceIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/posts/$postId/edit': {
      id: '/_app/posts/$postId/edit'
      path: '/posts/$postId/edit'
      fullPath: '/posts/$postId/edit'
      preLoaderRoute: typeof AppPostsPostIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/affaires-consulaires/profiles/$profileId': {
      id: '/_app/affaires-consulaires/profiles/$profileId'
      path: '/profiles/$profileId'
      fullPath: '/affaires-consulaires/profiles/$profileId'
      preLoaderRoute: typeof AppAffairesConsulairesProfilesProfileIdRouteImport
      parentRoute: typeof AppAffairesConsulairesRoute
    }
  }
}

interface AppAffairesConsulairesRouteChildren {
  AppAffairesConsulairesProfilesProfileIdRoute: typeof AppAffairesConsulairesProfilesProfileIdRoute
  AppAffairesConsulairesProfilesIndexRoute: typeof AppAffairesConsulairesProfilesIndexRoute
}

const AppAffairesConsulairesRouteChildren: AppAffairesConsulairesRouteChildren =
  {
    AppAffairesConsulairesProfilesProfileIdRoute:
      AppAffairesConsulairesProfilesProfileIdRoute,
    AppAffairesConsulairesProfilesIndexRoute:
      AppAffairesConsulairesProfilesIndexRoute,
  }

const AppAffairesConsulairesRouteWithChildren =
  AppAffairesConsulairesRoute._addFileChildren(
    AppAffairesConsulairesRouteChildren,
  )

interface AppRouteChildren {
  AppAffairesConsulairesRoute: typeof AppAffairesConsulairesRouteWithChildren
  AppAffairesDiplomatiquesRoute: typeof AppAffairesDiplomatiquesRoute
  AppCallsRoute: typeof AppCallsRoute
  AppIagendaRoute: typeof AppIagendaRoute
  AppIarchiveRoute: typeof AppIarchiveRoute
  AppIastedRoute: typeof AppIastedRoute
  AppIboiteRoute: typeof AppIboiteRoute
  AppIcorrespondanceRoute: typeof AppIcorrespondanceRoute
  AppIdocumentRoute: typeof AppIdocumentRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppStatisticsRoute: typeof AppStatisticsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAppointmentsAppointmentIdRoute: typeof AppAppointmentsAppointmentIdRoute
  AppAppointmentsAgentSchedulesRoute: typeof AppAppointmentsAgentSchedulesRoute
  AppConsularRegistryPrintQueueRoute: typeof AppConsularRegistryPrintQueueRoute
  AppPostsNewRoute: typeof AppPostsNewRoute
  AppProfilesProfileIdRoute: typeof AppProfilesProfileIdRoute
  AppRequestsReferenceRoute: typeof AppRequestsReferenceRoute
  AppAppointmentsIndexRoute: typeof AppAppointmentsIndexRoute
  AppConsularRegistryIndexRoute: typeof AppConsularRegistryIndexRoute
  AppMeetingsIndexRoute: typeof AppMeetingsIndexRoute
  AppPostsIndexRoute: typeof AppPostsIndexRoute
  AppRequestsIndexRoute: typeof AppRequestsIndexRoute
  AppServicesIndexRoute: typeof AppServicesIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppTeamIndexRoute: typeof AppTeamIndexRoute
  AppPostsPostIdEditRoute: typeof AppPostsPostIdEditRoute
  AppServicesServiceIdEditRoute: typeof AppServicesServiceIdEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAffairesConsulairesRoute: AppAffairesConsulairesRouteWithChildren,
  AppAffairesDiplomatiquesRoute: AppAffairesDiplomatiquesRoute,
  AppCallsRoute: AppCallsRoute,
  AppIagendaRoute: AppIagendaRoute,
  AppIarchiveRoute: AppIarchiveRoute,
  AppIastedRoute: AppIastedRoute,
  AppIboiteRoute: AppIboiteRoute,
  AppIcorrespondanceRoute: AppIcorrespondanceRoute,
  AppIdocumentRoute: AppIdocumentRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppStatisticsRoute: AppStatisticsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAppointmentsAppointmentIdRoute: AppAppointmentsAppointmentIdRoute,
  AppAppointmentsAgentSchedulesRoute: AppAppointmentsAgentSchedulesRoute,
  AppConsularRegistryPrintQueueRoute: AppConsularRegistryPrintQueueRoute,
  AppPostsNewRoute: AppPostsNewRoute,
  AppProfilesProfileIdRoute: AppProfilesProfileIdRoute,
  AppRequestsReferenceRoute: AppRequestsReferenceRoute,
  AppAppointmentsIndexRoute: AppAppointmentsIndexRoute,
  AppConsularRegistryIndexRoute: AppConsularRegistryIndexRoute,
  AppMeetingsIndexRoute: AppMeetingsIndexRoute,
  AppPostsIndexRoute: AppPostsIndexRoute,
  AppRequestsIndexRoute: AppRequestsIndexRoute,
  AppServicesIndexRoute: AppServicesIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppTeamIndexRoute: AppTeamIndexRoute,
  AppPostsPostIdEditRoute: AppPostsPostIdEditRoute,
  AppServicesServiceIdEditRoute: AppServicesServiceIdEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDevSignInRoute: ApiDevSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
