/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as MySpaceRouteImport } from './routes/my-space'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as InformationRouteImport } from './routes/information'
import { Route as FormulairesRouteImport } from './routes/formulaires'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AccessibiliteRouteImport } from './routes/accessibilite'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as OrgsIndexRouteImport } from './routes/orgs/index'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as MySpaceIndexRouteImport } from './routes/my-space/index'
import { Route as AcademyIndexRouteImport } from './routes/academy/index'
import { Route as VerifyTokenRouteImport } from './routes/verify.$token'
import { Route as VerifyProfileProfileIdRouteImport } from './routes/verify-profile.$profileId'
import { Route as SignUpSplatRouteImport } from './routes/sign-up/$'
import { Route as SignInSplatRouteImport } from './routes/sign-in/$'
import { Route as ServicesSlugRouteImport } from './routes/services/$slug'
import { Route as OrgsSlugRouteImport } from './routes/orgs/$slug'
import { Route as NewsSlugRouteImport } from './routes/news/$slug'
import { Route as MySpaceVaultRouteImport } from './routes/my-space/vault'
import { Route as MySpaceSettingsRouteImport } from './routes/my-space/settings'
import { Route as MySpaceServicesDemarchesRouteImport } from './routes/my-space/services-demarches'
import { Route as MySpaceRequestsRouteImport } from './routes/my-space/requests'
import { Route as MySpaceNotificationsRouteImport } from './routes/my-space/notifications'
import { Route as MySpaceMeetingsRouteImport } from './routes/my-space/meetings'
import { Route as MySpaceIdocumentRouteImport } from './routes/my-space/idocument'
import { Route as MySpaceIboiteRouteImport } from './routes/my-space/iboite'
import { Route as MySpaceIastedRouteImport } from './routes/my-space/iasted'
import { Route as MySpaceIagendaRouteImport } from './routes/my-space/iagenda'
import { Route as MySpaceDemarchesRouteImport } from './routes/my-space/demarches'
import { Route as MySpaceCvRouteImport } from './routes/my-space/cv'
import { Route as MySpaceCompaniesRouteImport } from './routes/my-space/companies'
import { Route as MySpaceChildrenRouteImport } from './routes/my-space/children'
import { Route as MySpaceAssociationsRouteImport } from './routes/my-space/associations'
import { Route as AcademySlugRouteImport } from './routes/academy/$slug'
import { Route as MySpaceSupportIndexRouteImport } from './routes/my-space/support/index'
import { Route as MySpaceServicesIndexRouteImport } from './routes/my-space/services/index'
import { Route as MySpaceAppointmentsIndexRouteImport } from './routes/my-space/appointments/index'
import { Route as MySpaceSupportNewRouteImport } from './routes/my-space/support/new'
import { Route as MySpaceSupportTicketIdRouteImport } from './routes/my-space/support/$ticketId'
import { Route as MySpaceRequestsReferenceRouteImport } from './routes/my-space/requests/$reference'
import { Route as MySpaceProfileEditRouteImport } from './routes/my-space/profile/edit'
import { Route as MySpaceDemarchesNewRouteImport } from './routes/my-space/demarches.new'
import { Route as MySpaceDemarchesDossierIdRouteImport } from './routes/my-space/demarches.$dossierId'
import { Route as MySpaceCompaniesIdRouteImport } from './routes/my-space/companies_.$id'
import { Route as MySpaceChildrenChildIdRouteImport } from './routes/my-space/children.$childId'
import { Route as MySpaceAssociationsSlugRouteImport } from './routes/my-space/associations_.$slug'
import { Route as MySpaceAppointmentsNewRouteImport } from './routes/my-space/appointments/new'
import { Route as MySpaceAppointmentsBookRouteImport } from './routes/my-space/appointments/book'
import { Route as MySpaceAppointmentsAppointmentIdRouteImport } from './routes/my-space/appointments/$appointmentId'
import { Route as ListingProfilesIdRouteImport } from './routes/listing.profiles.$id'
import { Route as ApiDevSignInRouteImport } from './routes/api/dev/sign-in'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as MySpaceServicesSlugNewRouteImport } from './routes/my-space/services/$slug.new'
import { Route as MySpaceRequestsRequestIdAppointmentRouteImport } from './routes/my-space/requests/$requestId_.appointment'

const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const MySpaceRoute = MySpaceRouteImport.update({
  id: '/my-space',
  path: '/my-space',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const InformationRoute = InformationRouteImport.update({
  id: '/information',
  path: '/information',
  getParentRoute: () => rootRouteImport,
} as any)
const FormulairesRoute = FormulairesRouteImport.update({
  id: '/formulaires',
  path: '/formulaires',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibiliteRoute = AccessibiliteRouteImport.update({
  id: '/accessibilite',
  path: '/accessibilite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsIndexRoute = OrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const MySpaceIndexRoute = MySpaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MySpaceRoute,
} as any)
const AcademyIndexRoute = AcademyIndexRouteImport.update({
  id: '/academy/',
  path: '/academy/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyTokenRoute = VerifyTokenRouteImport.update({
  id: '/verify/$token',
  path: '/verify/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyProfileProfileIdRoute = VerifyProfileProfileIdRouteImport.update({
  id: '/verify-profile/$profileId',
  path: '/verify-profile/$profileId',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsSlugRoute = OrgsSlugRouteImport.update({
  id: '/orgs/$slug',
  path: '/orgs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MySpaceVaultRoute = MySpaceVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => MySpaceRoute,
} as any)
const MySpaceSettingsRoute = MySpaceSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MySpaceRoute,
} as any)
const MySpaceServicesDemarchesRoute =
  MySpaceServicesDemarchesRouteImport.update({
    id: '/services-demarches',
    path: '/services-demarches',
    getParentRoute: () => MySpaceRoute,
  } as any)
const MySpaceRequestsRoute = MySpaceRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => MySpaceRoute,
} as any)
const MySpaceNotificationsRoute = MySpaceNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => MySpaceRoute,
} as any)
const MySpaceMeetingsRoute = MySpaceMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => MySpaceRoute,
} as any)
const MySpaceIdocumentRoute = MySpaceIdocumentRouteImport.update({
  id: '/idocument',
  path: '/idocument',
  getParentRoute: () => MySpaceRoute,
} as any)
const MySpaceIboiteRoute = MySpaceIboiteRouteImport.update({
  id: '/iboite',
  path: '/iboite',
  getParentRoute: () => MySpaceRoute,
} as any)
const MySpaceIastedRoute = MySpaceIastedRouteImport.update({
  id: '/iasted',
  path: '/iasted',
  getParentRoute: () => MySpaceRoute,
} as any)
const MySpaceIagendaRoute = MySpaceIagendaRouteImport.update({
  id: '/iagenda',
  path: '/iagenda',
  getParentRoute: () => MySpaceRoute,
} as any)
const MySpaceDemarchesRoute = MySpaceDemarchesRouteImport.update({
  id: '/demarches',
  path: '/demarches',
  getParentRoute: () => MySpaceRoute,
} as any)
const MySpaceCvRoute = MySpaceCvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => MySpaceRoute,
} as any)
const MySpaceCompaniesRoute = MySpaceCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => MySpaceRoute,
} as any)
const MySpaceChildrenRoute = MySpaceChildrenRouteImport.update({
  id: '/children',
  path: '/children',
  getParentRoute: () => MySpaceRoute,
} as any)
const MySpaceAssociationsRoute = MySpaceAssociationsRouteImport.update({
  id: '/associations',
  path: '/associations',
  getParentRoute: () => MySpaceRoute,
} as any)
const AcademySlugRoute = AcademySlugRouteImport.update({
  id: '/academy/$slug',
  path: '/academy/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MySpaceSupportIndexRoute = MySpaceSupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => MySpaceRoute,
} as any)
const MySpaceServicesIndexRoute = MySpaceServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => MySpaceRoute,
} as any)
const MySpaceAppointmentsIndexRoute =
  MySpaceAppointmentsIndexRouteImport.update({
    id: '/appointments/',
    path: '/appointments/',
    getParentRoute: () => MySpaceRoute,
  } as any)
const MySpaceSupportNewRoute = MySpaceSupportNewRouteImport.update({
  id: '/support/new',
  path: '/support/new',
  getParentRoute: () => MySpaceRoute,
} as any)
const MySpaceSupportTicketIdRoute = MySpaceSupportTicketIdRouteImport.update({
  id: '/support/$ticketId',
  path: '/support/$ticketId',
  getParentRoute: () => MySpaceRoute,
} as any)
const MySpaceRequestsReferenceRoute =
  MySpaceRequestsReferenceRouteImport.update({
    id: '/$reference',
    path: '/$reference',
    getParentRoute: () => MySpaceRequestsRoute,
  } as any)
const MySpaceProfileEditRoute = MySpaceProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => MySpaceRoute,
} as any)
const MySpaceDemarchesNewRoute = MySpaceDemarchesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MySpaceDemarchesRoute,
} as any)
const MySpaceDemarchesDossierIdRoute =
  MySpaceDemarchesDossierIdRouteImport.update({
    id: '/$dossierId',
    path: '/$dossierId',
    getParentRoute: () => MySpaceDemarchesRoute,
  } as any)
const MySpaceCompaniesIdRoute = MySpaceCompaniesIdRouteImport.update({
  id: '/companies_/$id',
  path: '/companies/$id',
  getParentRoute: () => MySpaceRoute,
} as any)
const MySpaceChildrenChildIdRoute = MySpaceChildrenChildIdRouteImport.update({
  id: '/$childId',
  path: '/$childId',
  getParentRoute: () => MySpaceChildrenRoute,
} as any)
const MySpaceAssociationsSlugRoute = MySpaceAssociationsSlugRouteImport.update({
  id: '/associations_/$slug',
  path: '/associations/$slug',
  getParentRoute: () => MySpaceRoute,
} as any)
const MySpaceAppointmentsNewRoute = MySpaceAppointmentsNewRouteImport.update({
  id: '/appointments/new',
  path: '/appointments/new',
  getParentRoute: () => MySpaceRoute,
} as any)
const MySpaceAppointmentsBookRoute = MySpaceAppointmentsBookRouteImport.update({
  id: '/appointments/book',
  path: '/appointments/book',
  getParentRoute: () => MySpaceRoute,
} as any)
const MySpaceAppointmentsAppointmentIdRoute =
  MySpaceAppointmentsAppointmentIdRouteImport.update({
    id: '/appointments/$appointmentId',
    path: '/appointments/$appointmentId',
    getParentRoute: () => MySpaceRoute,
  } as any)
const ListingProfilesIdRoute = ListingProfilesIdRouteImport.update({
  id: '/listing/profiles/$id',
  path: '/listing/profiles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevSignInRoute = ApiDevSignInRouteImport.update({
  id: '/api/dev/sign-in',
  path: '/api/dev/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MySpaceServicesSlugNewRoute = MySpaceServicesSlugNewRouteImport.update({
  id: '/services/$slug/new',
  path: '/services/$slug/new',
  getParentRoute: () => MySpaceRoute,
} as any)
const MySpaceRequestsRequestIdAppointmentRoute =
  MySpaceRequestsRequestIdAppointmentRouteImport.update({
    id: '/$requestId_/appointment',
    path: '/$requestId/appointment',
    getParentRoute: () => MySpaceRequestsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibilite': typeof AccessibiliteRoute
  '/community': typeof CommunityRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/faq': typeof FaqRoute
  '/formulaires': typeof FormulairesRoute
  '/information': typeof InformationRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/my-space': typeof MySpaceRouteWithChildren
  '/tarifs': typeof TarifsRoute
  '/academy/$slug': typeof AcademySlugRoute
  '/my-space/associations': typeof MySpaceAssociationsRoute
  '/my-space/children': typeof MySpaceChildrenRouteWithChildren
  '/my-space/companies': typeof MySpaceCompaniesRoute
  '/my-space/cv': typeof MySpaceCvRoute
  '/my-space/demarches': typeof MySpaceDemarchesRouteWithChildren
  '/my-space/iagenda': typeof MySpaceIagendaRoute
  '/my-space/iasted': typeof MySpaceIastedRoute
  '/my-space/iboite': typeof MySpaceIboiteRoute
  '/my-space/idocument': typeof MySpaceIdocumentRoute
  '/my-space/meetings': typeof MySpaceMeetingsRoute
  '/my-space/notifications': typeof MySpaceNotificationsRoute
  '/my-space/requests': typeof MySpaceRequestsRouteWithChildren
  '/my-space/services-demarches': typeof MySpaceServicesDemarchesRoute
  '/my-space/settings': typeof MySpaceSettingsRoute
  '/my-space/vault': typeof MySpaceVaultRoute
  '/news/$slug': typeof NewsSlugRoute
  '/orgs/$slug': typeof OrgsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/verify-profile/$profileId': typeof VerifyProfileProfileIdRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/academy/': typeof AcademyIndexRoute
  '/my-space/': typeof MySpaceIndexRoute
  '/news/': typeof NewsIndexRoute
  '/orgs/': typeof OrgsIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/dev/sign-in': typeof ApiDevSignInRoute
  '/listing/profiles/$id': typeof ListingProfilesIdRoute
  '/my-space/appointments/$appointmentId': typeof MySpaceAppointmentsAppointmentIdRoute
  '/my-space/appointments/book': typeof MySpaceAppointmentsBookRoute
  '/my-space/appointments/new': typeof MySpaceAppointmentsNewRoute
  '/my-space/associations/$slug': typeof MySpaceAssociationsSlugRoute
  '/my-space/children/$childId': typeof MySpaceChildrenChildIdRoute
  '/my-space/companies/$id': typeof MySpaceCompaniesIdRoute
  '/my-space/demarches/$dossierId': typeof MySpaceDemarchesDossierIdRoute
  '/my-space/demarches/new': typeof MySpaceDemarchesNewRoute
  '/my-space/profile/edit': typeof MySpaceProfileEditRoute
  '/my-space/requests/$reference': typeof MySpaceRequestsReferenceRoute
  '/my-space/support/$ticketId': typeof MySpaceSupportTicketIdRoute
  '/my-space/support/new': typeof MySpaceSupportNewRoute
  '/my-space/appointments/': typeof MySpaceAppointmentsIndexRoute
  '/my-space/services/': typeof MySpaceServicesIndexRoute
  '/my-space/support/': typeof MySpaceSupportIndexRoute
  '/my-space/requests/$requestId/appointment': typeof MySpaceRequestsRequestIdAppointmentRoute
  '/my-space/services/$slug/new': typeof MySpaceServicesSlugNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibilite': typeof AccessibiliteRoute
  '/community': typeof CommunityRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/faq': typeof FaqRoute
  '/formulaires': typeof FormulairesRoute
  '/information': typeof InformationRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/tarifs': typeof TarifsRoute
  '/academy/$slug': typeof AcademySlugRoute
  '/my-space/associations': typeof MySpaceAssociationsRoute
  '/my-space/children': typeof MySpaceChildrenRouteWithChildren
  '/my-space/companies': typeof MySpaceCompaniesRoute
  '/my-space/cv': typeof MySpaceCvRoute
  '/my-space/demarches': typeof MySpaceDemarchesRouteWithChildren
  '/my-space/iagenda': typeof MySpaceIagendaRoute
  '/my-space/iasted': typeof MySpaceIastedRoute
  '/my-space/iboite': typeof MySpaceIboiteRoute
  '/my-space/idocument': typeof MySpaceIdocumentRoute
  '/my-space/meetings': typeof MySpaceMeetingsRoute
  '/my-space/notifications': typeof MySpaceNotificationsRoute
  '/my-space/requests': typeof MySpaceRequestsRouteWithChildren
  '/my-space/services-demarches': typeof MySpaceServicesDemarchesRoute
  '/my-space/settings': typeof MySpaceSettingsRoute
  '/my-space/vault': typeof MySpaceVaultRoute
  '/news/$slug': typeof NewsSlugRoute
  '/orgs/$slug': typeof OrgsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/verify-profile/$profileId': typeof VerifyProfileProfileIdRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/academy': typeof AcademyIndexRoute
  '/my-space': typeof MySpaceIndexRoute
  '/news': typeof NewsIndexRoute
  '/orgs': typeof OrgsIndexRoute
  '/register': typeof RegisterIndexRoute
  '/services': typeof ServicesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/dev/sign-in': typeof ApiDevSignInRoute
  '/listing/profiles/$id': typeof ListingProfilesIdRoute
  '/my-space/appointments/$appointmentId': typeof MySpaceAppointmentsAppointmentIdRoute
  '/my-space/appointments/book': typeof MySpaceAppointmentsBookRoute
  '/my-space/appointments/new': typeof MySpaceAppointmentsNewRoute
  '/my-space/associations/$slug': typeof MySpaceAssociationsSlugRoute
  '/my-space/children/$childId': typeof MySpaceChildrenChildIdRoute
  '/my-space/companies/$id': typeof MySpaceCompaniesIdRoute
  '/my-space/demarches/$dossierId': typeof MySpaceDemarchesDossierIdRoute
  '/my-space/demarches/new': typeof MySpaceDemarchesNewRoute
  '/my-space/profile/edit': typeof MySpaceProfileEditRoute
  '/my-space/requests/$reference': typeof MySpaceRequestsReferenceRoute
  '/my-space/support/$ticketId': typeof MySpaceSupportTicketIdRoute
  '/my-space/support/new': typeof MySpaceSupportNewRoute
  '/my-space/appointments': typeof MySpaceAppointmentsIndexRoute
  '/my-space/services': typeof MySpaceServicesIndexRoute
  '/my-space/support': typeof MySpaceSupportIndexRoute
  '/my-space/requests/$requestId/appointment': typeof MySpaceRequestsRequestIdAppointmentRoute
  '/my-space/services/$slug/new': typeof MySpaceServicesSlugNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessibilite': typeof AccessibiliteRoute
  '/community': typeof CommunityRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/faq': typeof FaqRoute
  '/formulaires': typeof FormulairesRoute
  '/information': typeof InformationRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/my-space': typeof MySpaceRouteWithChildren
  '/tarifs': typeof TarifsRoute
  '/academy/$slug': typeof AcademySlugRoute
  '/my-space/associations': typeof MySpaceAssociationsRoute
  '/my-space/children': typeof MySpaceChildrenRouteWithChildren
  '/my-space/companies': typeof MySpaceCompaniesRoute
  '/my-space/cv': typeof MySpaceCvRoute
  '/my-space/demarches': typeof MySpaceDemarchesRouteWithChildren
  '/my-space/iagenda': typeof MySpaceIagendaRoute
  '/my-space/iasted': typeof MySpaceIastedRoute
  '/my-space/iboite': typeof MySpaceIboiteRoute
  '/my-space/idocument': typeof MySpaceIdocumentRoute
  '/my-space/meetings': typeof MySpaceMeetingsRoute
  '/my-space/notifications': typeof MySpaceNotificationsRoute
  '/my-space/requests': typeof MySpaceRequestsRouteWithChildren
  '/my-space/services-demarches': typeof MySpaceServicesDemarchesRoute
  '/my-space/settings': typeof MySpaceSettingsRoute
  '/my-space/vault': typeof MySpaceVaultRoute
  '/news/$slug': typeof NewsSlugRoute
  '/orgs/$slug': typeof OrgsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/verify-profile/$profileId': typeof VerifyProfileProfileIdRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/academy/': typeof AcademyIndexRoute
  '/my-space/': typeof MySpaceIndexRoute
  '/news/': typeof NewsIndexRoute
  '/orgs/': typeof OrgsIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/dev/sign-in': typeof ApiDevSignInRoute
  '/listing/profiles/$id': typeof ListingProfilesIdRoute
  '/my-space/appointments/$appointmentId': typeof MySpaceAppointmentsAppointmentIdRoute
  '/my-space/appointments/book': typeof MySpaceAppointmentsBookRoute
  '/my-space/appointments/new': typeof MySpaceAppointmentsNewRoute
  '/my-space/associations_/$slug': typeof MySpaceAssociationsSlugRoute
  '/my-space/children/$childId': typeof MySpaceChildrenChildIdRoute
  '/my-space/companies_/$id': typeof MySpaceCompaniesIdRoute
  '/my-space/demarches/$dossierId': typeof MySpaceDemarchesDossierIdRoute
  '/my-space/demarches/new': typeof MySpaceDemarchesNewRoute
  '/my-space/profile/edit': typeof MySpaceProfileEditRoute
  '/my-space/requests/$reference': typeof MySpaceRequestsReferenceRoute
  '/my-space/support/$ticketId': typeof MySpaceSupportTicketIdRoute
  '/my-space/support/new': typeof MySpaceSupportNewRoute
  '/my-space/appointments/': typeof MySpaceAppointmentsIndexRoute
  '/my-space/services/': typeof MySpaceServicesIndexRoute
  '/my-space/support/': typeof MySpaceSupportIndexRoute
  '/my-space/requests/$requestId_/appointment': typeof MySpaceRequestsRequestIdAppointmentRoute
  '/my-space/services/$slug/new': typeof MySpaceServicesSlugNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibilite'
    | '/community'
    | '/confidentialite'
    | '/faq'
    | '/formulaires'
    | '/information'
    | '/mentions-legales'
    | '/my-space'
    | '/tarifs'
    | '/academy/$slug'
    | '/my-space/associations'
    | '/my-space/children'
    | '/my-space/companies'
    | '/my-space/cv'
    | '/my-space/demarches'
    | '/my-space/iagenda'
    | '/my-space/iasted'
    | '/my-space/iboite'
    | '/my-space/idocument'
    | '/my-space/meetings'
    | '/my-space/notifications'
    | '/my-space/requests'
    | '/my-space/services-demarches'
    | '/my-space/settings'
    | '/my-space/vault'
    | '/news/$slug'
    | '/orgs/$slug'
    | '/services/$slug'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/verify-profile/$profileId'
    | '/verify/$token'
    | '/academy/'
    | '/my-space/'
    | '/news/'
    | '/orgs/'
    | '/register/'
    | '/services/'
    | '/api/auth/$'
    | '/api/dev/sign-in'
    | '/listing/profiles/$id'
    | '/my-space/appointments/$appointmentId'
    | '/my-space/appointments/book'
    | '/my-space/appointments/new'
    | '/my-space/associations/$slug'
    | '/my-space/children/$childId'
    | '/my-space/companies/$id'
    | '/my-space/demarches/$dossierId'
    | '/my-space/demarches/new'
    | '/my-space/profile/edit'
    | '/my-space/requests/$reference'
    | '/my-space/support/$ticketId'
    | '/my-space/support/new'
    | '/my-space/appointments/'
    | '/my-space/services/'
    | '/my-space/support/'
    | '/my-space/requests/$requestId/appointment'
    | '/my-space/services/$slug/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibilite'
    | '/community'
    | '/confidentialite'
    | '/faq'
    | '/formulaires'
    | '/information'
    | '/mentions-legales'
    | '/tarifs'
    | '/academy/$slug'
    | '/my-space/associations'
    | '/my-space/children'
    | '/my-space/companies'
    | '/my-space/cv'
    | '/my-space/demarches'
    | '/my-space/iagenda'
    | '/my-space/iasted'
    | '/my-space/iboite'
    | '/my-space/idocument'
    | '/my-space/meetings'
    | '/my-space/notifications'
    | '/my-space/requests'
    | '/my-space/services-demarches'
    | '/my-space/settings'
    | '/my-space/vault'
    | '/news/$slug'
    | '/orgs/$slug'
    | '/services/$slug'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/verify-profile/$profileId'
    | '/verify/$token'
    | '/academy'
    | '/my-space'
    | '/news'
    | '/orgs'
    | '/register'
    | '/services'
    | '/api/auth/$'
    | '/api/dev/sign-in'
    | '/listing/profiles/$id'
    | '/my-space/appointments/$appointmentId'
    | '/my-space/appointments/book'
    | '/my-space/appointments/new'
    | '/my-space/associations/$slug'
    | '/my-space/children/$childId'
    | '/my-space/companies/$id'
    | '/my-space/demarches/$dossierId'
    | '/my-space/demarches/new'
    | '/my-space/profile/edit'
    | '/my-space/requests/$reference'
    | '/my-space/support/$ticketId'
    | '/my-space/support/new'
    | '/my-space/appointments'
    | '/my-space/services'
    | '/my-space/support'
    | '/my-space/requests/$requestId/appointment'
    | '/my-space/services/$slug/new'
  id:
    | '__root__'
    | '/'
    | '/accessibilite'
    | '/community'
    | '/confidentialite'
    | '/faq'
    | '/formulaires'
    | '/information'
    | '/mentions-legales'
    | '/my-space'
    | '/tarifs'
    | '/academy/$slug'
    | '/my-space/associations'
    | '/my-space/children'
    | '/my-space/companies'
    | '/my-space/cv'
    | '/my-space/demarches'
    | '/my-space/iagenda'
    | '/my-space/iasted'
    | '/my-space/iboite'
    | '/my-space/idocument'
    | '/my-space/meetings'
    | '/my-space/notifications'
    | '/my-space/requests'
    | '/my-space/services-demarches'
    | '/my-space/settings'
    | '/my-space/vault'
    | '/news/$slug'
    | '/orgs/$slug'
    | '/services/$slug'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/verify-profile/$profileId'
    | '/verify/$token'
    | '/academy/'
    | '/my-space/'
    | '/news/'
    | '/orgs/'
    | '/register/'
    | '/services/'
    | '/api/auth/$'
    | '/api/dev/sign-in'
    | '/listing/profiles/$id'
    | '/my-space/appointments/$appointmentId'
    | '/my-space/appointments/book'
    | '/my-space/appointments/new'
    | '/my-space/associations_/$slug'
    | '/my-space/children/$childId'
    | '/my-space/companies_/$id'
    | '/my-space/demarches/$dossierId'
    | '/my-space/demarches/new'
    | '/my-space/profile/edit'
    | '/my-space/requests/$reference'
    | '/my-space/support/$ticketId'
    | '/my-space/support/new'
    | '/my-space/appointments/'
    | '/my-space/services/'
    | '/my-space/support/'
    | '/my-space/requests/$requestId_/appointment'
    | '/my-space/services/$slug/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessibiliteRoute: typeof AccessibiliteRoute
  CommunityRoute: typeof CommunityRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  FaqRoute: typeof FaqRoute
  FormulairesRoute: typeof FormulairesRoute
  InformationRoute: typeof InformationRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  MySpaceRoute: typeof MySpaceRouteWithChildren
  TarifsRoute: typeof TarifsRoute
  AcademySlugRoute: typeof AcademySlugRoute
  NewsSlugRoute: typeof NewsSlugRoute
  OrgsSlugRoute: typeof OrgsSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
  VerifyProfileProfileIdRoute: typeof VerifyProfileProfileIdRoute
  VerifyTokenRoute: typeof VerifyTokenRoute
  AcademyIndexRoute: typeof AcademyIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  OrgsIndexRoute: typeof OrgsIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDevSignInRoute: typeof ApiDevSignInRoute
  ListingProfilesIdRoute: typeof ListingProfilesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-space': {
      id: '/my-space'
      path: '/my-space'
      fullPath: '/my-space'
      preLoaderRoute: typeof MySpaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/information': {
      id: '/information'
      path: '/information'
      fullPath: '/information'
      preLoaderRoute: typeof InformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formulaires': {
      id: '/formulaires'
      path: '/formulaires'
      fullPath: '/formulaires'
      preLoaderRoute: typeof FormulairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibilite': {
      id: '/accessibilite'
      path: '/accessibilite'
      fullPath: '/accessibilite'
      preLoaderRoute: typeof AccessibiliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/': {
      id: '/orgs/'
      path: '/orgs'
      fullPath: '/orgs/'
      preLoaderRoute: typeof OrgsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-space/': {
      id: '/my-space/'
      path: '/'
      fullPath: '/my-space/'
      preLoaderRoute: typeof MySpaceIndexRouteImport
      parentRoute: typeof MySpaceRoute
    }
    '/academy/': {
      id: '/academy/'
      path: '/academy'
      fullPath: '/academy/'
      preLoaderRoute: typeof AcademyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$token': {
      id: '/verify/$token'
      path: '/verify/$token'
      fullPath: '/verify/$token'
      preLoaderRoute: typeof VerifyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-profile/$profileId': {
      id: '/verify-profile/$profileId'
      path: '/verify-profile/$profileId'
      fullPath: '/verify-profile/$profileId'
      preLoaderRoute: typeof VerifyProfileProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/$slug': {
      id: '/orgs/$slug'
      path: '/orgs/$slug'
      fullPath: '/orgs/$slug'
      preLoaderRoute: typeof OrgsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-space/vault': {
      id: '/my-space/vault'
      path: '/vault'
      fullPath: '/my-space/vault'
      preLoaderRoute: typeof MySpaceVaultRouteImport
      parentRoute: typeof MySpaceRoute
    }
    '/my-space/settings': {
      id: '/my-space/settings'
      path: '/settings'
      fullPath: '/my-space/settings'
      preLoaderRoute: typeof MySpaceSettingsRouteImport
      parentRoute: typeof MySpaceRoute
    }
    '/my-space/services-demarches': {
      id: '/my-space/services-demarches'
      path: '/services-demarches'
      fullPath: '/my-space/services-demarches'
      preLoaderRoute: typeof MySpaceServicesDemarchesRouteImport
      parentRoute: typeof MySpaceRoute
    }
    '/my-space/requests': {
      id: '/my-space/requests'
      path: '/requests'
      fullPath: '/my-space/requests'
      preLoaderRoute: typeof MySpaceRequestsRouteImport
      parentRoute: typeof MySpaceRoute
    }
    '/my-space/notifications': {
      id: '/my-space/notifications'
      path: '/notifications'
      fullPath: '/my-space/notifications'
      preLoaderRoute: typeof MySpaceNotificationsRouteImport
      parentRoute: typeof MySpaceRoute
    }
    '/my-space/meetings': {
      id: '/my-space/meetings'
      path: '/meetings'
      fullPath: '/my-space/meetings'
      preLoaderRoute: typeof MySpaceMeetingsRouteImport
      parentRoute: typeof MySpaceRoute
    }
    '/my-space/idocument': {
      id: '/my-space/idocument'
      path: '/idocument'
      fullPath: '/my-space/idocument'
      preLoaderRoute: typeof MySpaceIdocumentRouteImport
      parentRoute: typeof MySpaceRoute
    }
    '/my-space/iboite': {
      id: '/my-space/iboite'
      path: '/iboite'
      fullPath: '/my-space/iboite'
      preLoaderRoute: typeof MySpaceIboiteRouteImport
      parentRoute: typeof MySpaceRoute
    }
    '/my-space/iasted': {
      id: '/my-space/iasted'
      path: '/iasted'
      fullPath: '/my-space/iasted'
      preLoaderRoute: typeof MySpaceIastedRouteImport
      parentRoute: typeof MySpaceRoute
    }
    '/my-space/iagenda': {
      id: '/my-space/iagenda'
      path: '/iagenda'
      fullPath: '/my-space/iagenda'
      preLoaderRoute: typeof MySpaceIagendaRouteImport
      parentRoute: typeof MySpaceRoute
    }
    '/my-space/demarches': {
      id: '/my-space/demarches'
      path: '/demarches'
      fullPath: '/my-space/demarches'
      preLoaderRoute: typeof MySpaceDemarchesRouteImport
      parentRoute: typeof MySpaceRoute
    }
    '/my-space/cv': {
      id: '/my-space/cv'
      path: '/cv'
      fullPath: '/my-space/cv'
      preLoaderRoute: typeof MySpaceCvRouteImport
      parentRoute: typeof MySpaceRoute
    }
    '/my-space/companies': {
      id: '/my-space/companies'
      path: '/companies'
      fullPath: '/my-space/companies'
      preLoaderRoute: typeof MySpaceCompaniesRouteImport
      parentRoute: typeof MySpaceRoute
    }
    '/my-space/children': {
      id: '/my-space/children'
      path: '/children'
      fullPath: '/my-space/children'
      preLoaderRoute: typeof MySpaceChildrenRouteImport
      parentRoute: typeof MySpaceRoute
    }
    '/my-space/associations': {
      id: '/my-space/associations'
      path: '/associations'
      fullPath: '/my-space/associations'
      preLoaderRoute: typeof MySpaceAssociationsRouteImport
      parentRoute: typeof MySpaceRoute
    }
    '/academy/$slug': {
      id: '/academy/$slug'
      path: '/academy/$slug'
      fullPath: '/academy/$slug'
      preLoaderRoute: typeof AcademySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-space/support/': {
      id: '/my-space/support/'
      path: '/support'
      fullPath: '/my-space/support/'
      preLoaderRoute: typeof MySpaceSupportIndexRouteImport
      parentRoute: typeof MySpaceRoute
    }
    '/my-space/services/': {
      id: '/my-space/services/'
      path: '/services'
      fullPath: '/my-space/services/'
      preLoaderRoute: typeof MySpaceServicesIndexRouteImport
      parentRoute: typeof MySpaceRoute
    }
    '/my-space/appointments/': {
      id: '/my-space/appointments/'
      path: '/appointments'
      fullPath: '/my-space/appointments/'
      preLoaderRoute: typeof MySpaceAppointmentsIndexRouteImport
      parentRoute: typeof MySpaceRoute
    }
    '/my-space/support/new': {
      id: '/my-space/support/new'
      path: '/support/new'
      fullPath: '/my-space/support/new'
      preLoaderRoute: typeof MySpaceSupportNewRouteImport
      parentRoute: typeof MySpaceRoute
    }
    '/my-space/support/$ticketId': {
      id: '/my-space/support/$ticketId'
      path: '/support/$ticketId'
      fullPath: '/my-space/support/$ticketId'
      preLoaderRoute: typeof MySpaceSupportTicketIdRouteImport
      parentRoute: typeof MySpaceRoute
    }
    '/my-space/requests/$reference': {
      id: '/my-space/requests/$reference'
      path: '/$reference'
      fullPath: '/my-space/requests/$reference'
      preLoaderRoute: typeof MySpaceRequestsReferenceRouteImport
      parentRoute: typeof MySpaceRequestsRoute
    }
    '/my-space/profile/edit': {
      id: '/my-space/profile/edit'
      path: '/profile/edit'
      fullPath: '/my-space/profile/edit'
      preLoaderRoute: typeof MySpaceProfileEditRouteImport
      parentRoute: typeof MySpaceRoute
    }
    '/my-space/demarches/new': {
      id: '/my-space/demarches/new'
      path: '/new'
      fullPath: '/my-space/demarches/new'
      preLoaderRoute: typeof MySpaceDemarchesNewRouteImport
      parentRoute: typeof MySpaceDemarchesRoute
    }
    '/my-space/demarches/$dossierId': {
      id: '/my-space/demarches/$dossierId'
      path: '/$dossierId'
      fullPath: '/my-space/demarches/$dossierId'
      preLoaderRoute: typeof MySpaceDemarchesDossierIdRouteImport
      parentRoute: typeof MySpaceDemarchesRoute
    }
    '/my-space/companies_/$id': {
      id: '/my-space/companies_/$id'
      path: '/companies/$id'
      fullPath: '/my-space/companies/$id'
      preLoaderRoute: typeof MySpaceCompaniesIdRouteImport
      parentRoute: typeof MySpaceRoute
    }
    '/my-space/children/$childId': {
      id: '/my-space/children/$childId'
      path: '/$childId'
      fullPath: '/my-space/children/$childId'
      preLoaderRoute: typeof MySpaceChildrenChildIdRouteImport
      parentRoute: typeof MySpaceChildrenRoute
    }
    '/my-space/associations_/$slug': {
      id: '/my-space/associations_/$slug'
      path: '/associations/$slug'
      fullPath: '/my-space/associations/$slug'
      preLoaderRoute: typeof MySpaceAssociationsSlugRouteImport
      parentRoute: typeof MySpaceRoute
    }
    '/my-space/appointments/new': {
      id: '/my-space/appointments/new'
      path: '/appointments/new'
      fullPath: '/my-space/appointments/new'
      preLoaderRoute: typeof MySpaceAppointmentsNewRouteImport
      parentRoute: typeof MySpaceRoute
    }
    '/my-space/appointments/book': {
      id: '/my-space/appointments/book'
      path: '/appointments/book'
      fullPath: '/my-space/appointments/book'
      preLoaderRoute: typeof MySpaceAppointmentsBookRouteImport
      parentRoute: typeof MySpaceRoute
    }
    '/my-space/appointments/$appointmentId': {
      id: '/my-space/appointments/$appointmentId'
      path: '/appointments/$appointmentId'
      fullPath: '/my-space/appointments/$appointmentId'
      preLoaderRoute: typeof MySpaceAppointmentsAppointmentIdRouteImport
      parentRoute: typeof MySpaceRoute
    }
    '/listing/profiles/$id': {
      id: '/listing/profiles/$id'
      path: '/listing/profiles/$id'
      fullPath: '/listing/profiles/$id'
      preLoaderRoute: typeof ListingProfilesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev/sign-in': {
      id: '/api/dev/sign-in'
      path: '/api/dev/sign-in'
      fullPath: '/api/dev/sign-in'
      preLoaderRoute: typeof ApiDevSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-space/services/$slug/new': {
      id: '/my-space/services/$slug/new'
      path: '/services/$slug/new'
      fullPath: '/my-space/services/$slug/new'
      preLoaderRoute: typeof MySpaceServicesSlugNewRouteImport
      parentRoute: typeof MySpaceRoute
    }
    '/my-space/requests/$requestId_/appointment': {
      id: '/my-space/requests/$requestId_/appointment'
      path: '/$requestId/appointment'
      fullPath: '/my-space/requests/$requestId/appointment'
      preLoaderRoute: typeof MySpaceRequestsRequestIdAppointmentRouteImport
      parentRoute: typeof MySpaceRequestsRoute
    }
  }
}

interface MySpaceChildrenRouteChildren {
  MySpaceChildrenChildIdRoute: typeof MySpaceChildrenChildIdRoute
}

const MySpaceChildrenRouteChildren: MySpaceChildrenRouteChildren = {
  MySpaceChildrenChildIdRoute: MySpaceChildrenChildIdRoute,
}

const MySpaceChildrenRouteWithChildren = MySpaceChildrenRoute._addFileChildren(
  MySpaceChildrenRouteChildren,
)

interface MySpaceDemarchesRouteChildren {
  MySpaceDemarchesDossierIdRoute: typeof MySpaceDemarchesDossierIdRoute
  MySpaceDemarchesNewRoute: typeof MySpaceDemarchesNewRoute
}

const MySpaceDemarchesRouteChildren: MySpaceDemarchesRouteChildren = {
  MySpaceDemarchesDossierIdRoute: MySpaceDemarchesDossierIdRoute,
  MySpaceDemarchesNewRoute: MySpaceDemarchesNewRoute,
}

const MySpaceDemarchesRouteWithChildren =
  MySpaceDemarchesRoute._addFileChildren(MySpaceDemarchesRouteChildren)

interface MySpaceRequestsRouteChildren {
  MySpaceRequestsReferenceRoute: typeof MySpaceRequestsReferenceRoute
  MySpaceRequestsRequestIdAppointmentRoute: typeof MySpaceRequestsRequestIdAppointmentRoute
}

const MySpaceRequestsRouteChildren: MySpaceRequestsRouteChildren = {
  MySpaceRequestsReferenceRoute: MySpaceRequestsReferenceRoute,
  MySpaceRequestsRequestIdAppointmentRoute:
    MySpaceRequestsRequestIdAppointmentRoute,
}

const MySpaceRequestsRouteWithChildren = MySpaceRequestsRoute._addFileChildren(
  MySpaceRequestsRouteChildren,
)

interface MySpaceRouteChildren {
  MySpaceAssociationsRoute: typeof MySpaceAssociationsRoute
  MySpaceChildrenRoute: typeof MySpaceChildrenRouteWithChildren
  MySpaceCompaniesRoute: typeof MySpaceCompaniesRoute
  MySpaceCvRoute: typeof MySpaceCvRoute
  MySpaceDemarchesRoute: typeof MySpaceDemarchesRouteWithChildren
  MySpaceIagendaRoute: typeof MySpaceIagendaRoute
  MySpaceIastedRoute: typeof MySpaceIastedRoute
  MySpaceIboiteRoute: typeof MySpaceIboiteRoute
  MySpaceIdocumentRoute: typeof MySpaceIdocumentRoute
  MySpaceMeetingsRoute: typeof MySpaceMeetingsRoute
  MySpaceNotificationsRoute: typeof MySpaceNotificationsRoute
  MySpaceRequestsRoute: typeof MySpaceRequestsRouteWithChildren
  MySpaceServicesDemarchesRoute: typeof MySpaceServicesDemarchesRoute
  MySpaceSettingsRoute: typeof MySpaceSettingsRoute
  MySpaceVaultRoute: typeof MySpaceVaultRoute
  MySpaceIndexRoute: typeof MySpaceIndexRoute
  MySpaceAppointmentsAppointmentIdRoute: typeof MySpaceAppointmentsAppointmentIdRoute
  MySpaceAppointmentsBookRoute: typeof MySpaceAppointmentsBookRoute
  MySpaceAppointmentsNewRoute: typeof MySpaceAppointmentsNewRoute
  MySpaceAssociationsSlugRoute: typeof MySpaceAssociationsSlugRoute
  MySpaceCompaniesIdRoute: typeof MySpaceCompaniesIdRoute
  MySpaceProfileEditRoute: typeof MySpaceProfileEditRoute
  MySpaceSupportTicketIdRoute: typeof MySpaceSupportTicketIdRoute
  MySpaceSupportNewRoute: typeof MySpaceSupportNewRoute
  MySpaceAppointmentsIndexRoute: typeof MySpaceAppointmentsIndexRoute
  MySpaceServicesIndexRoute: typeof MySpaceServicesIndexRoute
  MySpaceSupportIndexRoute: typeof MySpaceSupportIndexRoute
  MySpaceServicesSlugNewRoute: typeof MySpaceServicesSlugNewRoute
}

const MySpaceRouteChildren: MySpaceRouteChildren = {
  MySpaceAssociationsRoute: MySpaceAssociationsRoute,
  MySpaceChildrenRoute: MySpaceChildrenRouteWithChildren,
  MySpaceCompaniesRoute: MySpaceCompaniesRoute,
  MySpaceCvRoute: MySpaceCvRoute,
  MySpaceDemarchesRoute: MySpaceDemarchesRouteWithChildren,
  MySpaceIagendaRoute: MySpaceIagendaRoute,
  MySpaceIastedRoute: MySpaceIastedRoute,
  MySpaceIboiteRoute: MySpaceIboiteRoute,
  MySpaceIdocumentRoute: MySpaceIdocumentRoute,
  MySpaceMeetingsRoute: MySpaceMeetingsRoute,
  MySpaceNotificationsRoute: MySpaceNotificationsRoute,
  MySpaceRequestsRoute: MySpaceRequestsRouteWithChildren,
  MySpaceServicesDemarchesRoute: MySpaceServicesDemarchesRoute,
  MySpaceSettingsRoute: MySpaceSettingsRoute,
  MySpaceVaultRoute: MySpaceVaultRoute,
  MySpaceIndexRoute: MySpaceIndexRoute,
  MySpaceAppointmentsAppointmentIdRoute: MySpaceAppointmentsAppointmentIdRoute,
  MySpaceAppointmentsBookRoute: MySpaceAppointmentsBookRoute,
  MySpaceAppointmentsNewRoute: MySpaceAppointmentsNewRoute,
  MySpaceAssociationsSlugRoute: MySpaceAssociationsSlugRoute,
  MySpaceCompaniesIdRoute: MySpaceCompaniesIdRoute,
  MySpaceProfileEditRoute: MySpaceProfileEditRoute,
  MySpaceSupportTicketIdRoute: MySpaceSupportTicketIdRoute,
  MySpaceSupportNewRoute: MySpaceSupportNewRoute,
  MySpaceAppointmentsIndexRoute: MySpaceAppointmentsIndexRoute,
  MySpaceServicesIndexRoute: MySpaceServicesIndexRoute,
  MySpaceSupportIndexRoute: MySpaceSupportIndexRoute,
  MySpaceServicesSlugNewRoute: MySpaceServicesSlugNewRoute,
}

const MySpaceRouteWithChildren =
  MySpaceRoute._addFileChildren(MySpaceRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessibiliteRoute: AccessibiliteRoute,
  CommunityRoute: CommunityRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  FaqRoute: FaqRoute,
  FormulairesRoute: FormulairesRoute,
  InformationRoute: InformationRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  MySpaceRoute: MySpaceRouteWithChildren,
  TarifsRoute: TarifsRoute,
  AcademySlugRoute: AcademySlugRoute,
  NewsSlugRoute: NewsSlugRoute,
  OrgsSlugRoute: OrgsSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
  VerifyProfileProfileIdRoute: VerifyProfileProfileIdRoute,
  VerifyTokenRoute: VerifyTokenRoute,
  AcademyIndexRoute: AcademyIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  OrgsIndexRoute: OrgsIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDevSignInRoute: ApiDevSignInRoute,
  ListingProfilesIdRoute: ListingProfilesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
